PLAT-839: Fix small glitches
reciprocity/zen-ui pull request #109
Opened 2021-01-18 00:43 UTC by f-jauregui

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-839)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-19 13:34 UTC, chavlji requested changes
Looks nice, I'm just missing 2 things from the ticket:

3. should be able to have a button with icon only. Due to some of Jan's latest changes it's now broken (label is always visible and thus it's margin is applied)
4. 
6. Slots description: should be ON the left instead Slot for the icon at the left

2021-01-20 14:58 UTC, chavlji requested changes

2021-01-20 14:58 UTC, chavlji commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
No need for this story since it looks the same as the icon in the leading slot.

2021-01-20 14:58 UTC, chavlji commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
In this Figma designs this kind of button should be a perfect square:
![Screenshot 2021-01-20 at 15 55 19](https://user-images.githubusercontent.com/5729421/105192182-23b08800-5b38-11eb-80b5-5267c94da9c1.jpg)

2021-01-20 15:01 UTC, f-jauregui commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
So you think that button should modify its padding when the icon is not square?

2021-01-20 15:05 UTC, chavlji commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
Not sure what would be the best solution here...
I see no other solution but to check if only `leadingIcon` slot exists - has some nodes assigned (and nothing else - no `default` slot, no `trailingIcon` slot) and then apply some class that will take care of it.
We could provide another component called `zen-icon-button`, but imo it's more natural to have just one button component since we already provide `icon` slot in it.

2021-01-20 15:15 UTC, f-jauregui commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
Why not to have a zen-icon component that will deal with the icon box size?

Then you just go:
```js
<zen-button ...props>
  <zen-icon ...props>
    {ICON_GOES_HERE}
  </zen-icon>
</zen-button>
```

2021-01-20 15:16 UTC, f-jauregui commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
Done.

2021-01-20 15:24 UTC, chavlji commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
Remember when I said it would be better to just expose slot `content` instead of `leading`, `trailing` thing? ;)

Imo that the right and most natural way, yeah. To just have a default slot and that's it.

We should think of how we'll control the spacing between icon and label? Designers expect that to be standardized. Might be best to use css sth like:
`:slotted{ .zen-icon + * { margin-left: 1rem; }}`
And app can override that if it needs to.
 
But we need `zen-icon` component anyway. The task is already there for quite some time.

2021-01-20 15:40 UTC, chavlji approved these changes
We'll take care of icon-only buttons in the next PR.

2021-01-20 15:58 UTC, f-jauregui commented on src/components/zen-button/zen-button.stories.mdx
> +      <div style="display: flex; flex-direction: column; align-items: center;">
Created zen-icon story in https://reciprocitylabs.atlassian.net/browse/PLAT-935 to tackle this, since it doesn't exist.

2021-01-20 15:58 UTC, merged