BAN-164: Fix existing and improve incomplete tests
reciprocity/zen-ui pull request #113
Opened 2021-01-20 17:56 UTC by f-jauregui

Updated tests for:

- input
- checkbox
- button
- textarea
- spinner
- label
- support text

[JIRA Ticket - Fix existing tests](https://reciprocitylabs.atlassian.net/browse/BAN-164)
[JIRA Ticket - Improve incomplete tests](https://reciprocitylabs.atlassian.net/browse/BAN-165)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-20 17:59 UTC, mihaelpalfi approved these changes
Now it looks like unit tests. Great job Fermin!

2021-01-20 18:09 UTC, mplesec approved these changes
![Screenshot 2021-01-20 at 19 09 02](https://user-images.githubusercontent.com/9392804/105216531-fae9bc00-5b52-11eb-92dc-de38320187b2.png)

2021-01-21 08:43 UTC, chavlji requested changes
I'm not sure. A lot of these tests just set HTML through a template string and then test if dom has things we've set in the template string.

They are just testing that converting a template string into HTML works, which means it's not a component unit test.

2021-01-21 08:43 UTC, chavlji commented on src/components/zen-checkbox/test/zen-checkbox.spec.tsx
> +    expect(page.root.getAttribute('disabled')).toBe('');
These tests aren't really testing much? You've setting the attr in html and then check that element has this attribute? Why wouldn't it?

Imo we should have this kind of tests just for one initial render...

2021-01-21 08:43 UTC, chavlji commented on src/components/zen-button/test/zen-button.spec.tsx
> +    expect(page.root.querySelector('[slot="leadingIcon"]')).toBeTruthy();
As mentioned. We're just checking if div has things we've set in the template string...

2021-01-21 10:42 UTC, f-jauregui commented on src/components/zen-button/test/zen-button.spec.tsx
> +    expect(page.root.querySelector('[slot="leadingIcon"]')).toBeTruthy();
This checks if an element is rendered outside the shadow dom with attribute slot set to leadingIcon. Should I remove this?

2021-01-21 10:43 UTC, f-jauregui commented on src/components/zen-checkbox/test/zen-checkbox.spec.tsx
> +    expect(page.root.getAttribute('disabled')).toBe('');
This check if props are being properly applied to the input. Should I remove it?

2021-01-21 11:24 UTC, chavlji commented on src/components/zen-checkbox/test/zen-checkbox.spec.tsx
> +    expect(page.root.getAttribute('disabled')).toBe('');
If you set it in the HTML template string, how can it not be set? Only if the parser fails, but this isn't our responsibility.
I'd remove all such tests because I can't see any value in them.

We've had a discussion with @mplesec that it might only be reasonable to test whether all expected props are still supported (so that we don't accidentally delete some prop). But they should all be tested in one test. Possibly using some helper function like:
``` expect(reflectsPropsOnAttributes(['value', 'disabled', 'variant']). toBeTruthy()```

2021-01-21 12:00 UTC, f-jauregui commented on src/components/zen-button/test/zen-button.spec.tsx
> +    expect(page.root.querySelector('[slot="leadingIcon"]')).toBeTruthy();
Removed it.

2021-01-21 12:00 UTC, f-jauregui commented on src/components/zen-checkbox/test/zen-checkbox.spec.tsx
> +    expect(page.root.getAttribute('disabled')).toBe('');
Done.

And please include me when this happens:

> We've had a discussion with @mplesec that it might only be reasonable to test whether all expected props are still supported (so that we don't accidentally delete some prop). But they should all be tested in one test. Possibly using some helper function like:
expect(reflectsPropsOnAttributes(['value', 'disabled', 'variant']). toBeTruthy()

2021-01-21 12:56 UTC, chavlji commented on src/components/zen-checkbox/test/zen-checkbox.spec.tsx
> +    expect(page.root.getAttribute('disabled')).toBe('');
Sure. We've had this discussion just today in the morning, so after this pr...

2021-01-21 14:49 UTC, chavlji approved these changes
👍🏻

2021-01-21 14:49 UTC, merged