PLAT-854: Add avatar component
reciprocity/zen-ui pull request #117
Opened 2021-01-21 12:38 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-854)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-21 18:20 UTC, f-jauregui reviewed
So far it looks really good. Nice job, Mihael!
Waiting for the tests now! 😎

2021-01-22 09:22 UTC, chavlji requested changes
Very nice! Looks great.

2021-01-22 09:22 UTC, chavlji commented on src/components/zen-avatar/zen-avatar.tsx
> +  @Prop() readonly label: string = '';
This prop should be `userName` instead. Component should provide the logic to extract the initials. Otherwise each app will need to implement it on it's own...
Sth like: `userName.match(/(\b([A-Z]|[a-z]))/g).join('').substring(0,2).toUpperCase()`

2021-01-22 09:22 UTC, chavlji commented on src/components/zen-avatar/zen-avatar.tsx
> +        <img class={{ hidden: !this.hasImage(), [this.size]: true }} src={this.imageUrl} />
No need for size classes. Not here nor on host element.
Use attribute selectors in the css instead:
`:host([size=md])` and `:host([size=md]) > img`
Also remove tests where you test if size classes are applied.

2021-01-22 09:22 UTC, chavlji commented on src/zen-styles/mixins/helpers.scss
> +  margin: $padding;
Why not just setting `width` and `height` instead of both `min/max-width`?

2021-01-22 09:22 UTC, chavlji commented on src/zen-styles/mixins/helpers.scss
> +@mixin round-icon($size, $padding: null) {
Move this mixin into `zen-avatar.scss` because it's very specific and not widely reusable.

2021-01-25 09:56 UTC, mihaelpalfi commented on src/components/helpers/types.ts
> +export type AvatarSize = 'medium' | 'large';
Changed.

2021-01-25 09:56 UTC, mihaelpalfi commented on src/components/zen-avatar/zen-avatar.tsx
> +  @Prop() readonly label: string = '';
Done

2021-01-25 09:57 UTC, mihaelpalfi commented on src/components/zen-avatar/zen-avatar.tsx
> +        <img class={{ hidden: !this.hasImage(), [this.size]: true }} src={this.imageUrl} />
Good one. Didnt know this is possible. Changed.

2021-01-25 10:03 UTC, mihaelpalfi commented on src/zen-styles/mixins/helpers.scss
> +@mixin round-icon($size, $padding: null) {
My opinion this is a helper mixin. It should be here if there is a need for it in the future. When its not somebody will put it there again and not remove the one from avatar component.

2021-01-25 15:02 UTC, mihaelpalfi commented on src/zen-styles/mixins/helpers.scss
> +  margin: $padding;
Changed.

2021-01-26 10:12 UTC, mplesec commented on src/components/zen-avatar/zen-avatar.tsx
> +  }
This assumes a username will have a space in? Also, please add some tests for this function.

2021-01-26 10:28 UTC, chavlji approved these changes

2021-01-26 10:28 UTC, chavlji commented on src/components/zen-avatar/zen-avatar.tsx
> +  }
It gets words using word boundary. So can be any character that breaks words.
Agree that tests should be added.

2021-01-26 10:28 UTC, chavlji commented on src/zen-styles/mixins/helpers.scss
> +@mixin round-icon($size, $padding: null) {
Ok. Maybe we should just use some different name for this mixin. Its content doesn't have any icon... `roundel`, `round-icon-wrapper` maybe? It should probably also need to take bg-color as a parameter, to be really useful?

2021-01-27 09:55 UTC, mihaelpalfi commented on src/components/zen-avatar/zen-avatar.tsx
> +  }
Added additional case that takes initials from email when username dosent exist. Also if no surname is provided. Added also tests fro all this cases.

2021-01-27 14:56 UTC, chavlji approved these changes
Nice!

Would be good to change those two things, but you can do it on the next ticket if you want.

Please if you can just add `noselect` mixin and `cursor: default`, so the initials can't be selected ...and we can merge it right away.

2021-01-27 14:56 UTC, chavlji commented on src/components/zen-avatar/zen-avatar.tsx
> +      initials = this.email.substring(0, 2).toUpperCase();
I'd expect that `jan.savli@gmail.com` to result in `JA`. I would expect `JS`.
To achieve this you can use the same function as for userName. Same regex...

2021-01-27 15:50 UTC, mihaelpalfi commented on src/components/zen-avatar/zen-avatar.tsx
> +      initials = this.email.substring(0, 2).toUpperCase();
Great suggestion. But requirement is that it should take first two letters of email.

2021-01-28 08:35 UTC, merged