BAN-166: Write component tests
reciprocity/zen-ui pull request #118
Opened 2021-01-21 15:53 UTC by chavlji

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-166)

2021-01-21 17:52 UTC, f-jauregui requested changes
Awesome work, Jan!
Just some little updates.

Regarding snapshot tests, I don't know if they are necessary to achieve certain coverage, so I just commented to remove them **if necessary**.

2021-01-21 17:52 UTC, f-jauregui commented on src/components/helpers/jest.ts
> +}
Nice! 👍

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-animate/test/zen-animate.spec.tsx
> +
Please add test for the show property.

2021-01-21 17:52 UTC, f-jauregui commented on src/components/helpers/helpers.ts
> +export function getSlotElement(host: HTMLElement, slotName?: string): HTMLElement | undefined {
This is a cool helper! 👍

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-dropdown/test/zen-dropdown.spec.tsx
> +    expect(page.root).toEqualHtml(`
Please remove snapshot test if it's not necessary.

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-dropdown/test/zen-dropdown.spec.tsx
> +  });
Good idea here! 🙌

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-menu-item/test/zen-option.spec.tsx
> +    expect(page.root).toEqualHtml(`<zen-option value="Graham">
Please remove snapshot test if it's not necessary.

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-menu-item/test/zen-option.spec.tsx
> +    expect(await propReflectsInAttributes(page, props)).toBeTruthy();
Loved this.

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-tabs/test/zen-tabs.spec.tsx
> +// import { propReflectsInAttributes } from '../../helpers/jest';
Please remove.

2021-01-21 17:52 UTC, f-jauregui commented on src/components/zen-tabs/test/zen-tabs.spec.tsx
> +});
Please remove snapshot test if it's not necessary.

2021-01-22 10:18 UTC, chavlji commented on src/components/zen-dropdown/test/zen-dropdown.spec.tsx
> +    expect(page.root).toEqualHtml(`
Good one! 🙌🏻

2021-01-22 13:40 UTC, mplesec approved these changes
Good work 👍

2021-01-23 14:57 UTC, f-jauregui approved these changes
Well done!

2021-01-23 14:58 UTC, merged