POC: PLAT-852: Zen Table
reciprocity/zen-ui pull request #122
Opened 2021-01-25 11:09 UTC by mplesec

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-852)

#### Description
Quick POC for the Zen Table components. Comment if you'd expect anything different, especially form the consumer's side.

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-25 11:30 UTC, chavlji reviewed
It looks ok in general.

One thing to consider:
- Component names are maybe too long and look too verbose in the HTML. What about `<zen-tr>` `<zen-td>` `<zen-th>`

2021-01-25 11:30 UTC, chavlji commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
Would it be possible to get rid of this wrapping table elements into host each time? So that Host itself becomes a td? It might be possible to set just the right css (display: table,...) and avoid tables altogether?

Is this syntax even correct? Shouldn't eg. `<tr>` always contain just `<td>` elements? In our case it contains `<zen-table-cell>` custom elements which isn't `<td>`:
```html
<table>
  <some-custom-element>
    <tr>
      <some-custom-element>
        <td />
      </some-custom-element>
      <some-custom-element>
        <td />
      </some-custom-element>
    </tr>
  </some-custom-element>
</table>
```

2021-01-25 12:33 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
Possible, check the latest commit. Note however that there are no `tr`, `th`, and `td` elements in the markup then (not sure if that's ok).

2021-01-25 12:36 UTC, leferreyra reviewed
I like the direction this is going, great work.

@chavlji I like long verbose names :P, these look great IMHO

2021-01-25 12:36 UTC, leferreyra commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
I think @chavlji is right about table elements only allowing for certain children types, see the [permitted content section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table)

2021-01-25 12:45 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
I think the only HTML valid approach then is to wrap a regular table element within a `ZenTable` custom element. The consumer would then add the markup in the same way as for a regular table. Like so:
```
<zen-table>
  <thead>
    <tr>
      <th>Foo</th>
      <th>Bar</th>
    </tr>
  </head>
  <tbody>
    <tr>
      <td>A</td>
      <td>1</td>
    </tr>
    <tr>
      <td>B</td>
      <td>2</td>
    </tr>
  </tbody>
</zen-table>
```

2021-01-25 12:59 UTC, leferreyra commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
I don't know if this is possible but rendering divs with the correct display could work, maybe worth looking into.

2021-01-25 13:18 UTC, chavlji commented
To me, this new commit looks great!
It also behaves as you'd expect it from the table:
![Screenshot 2021-01-25 at 14 16 01](https://user-images.githubusercontent.com/5729421/105710949-1f111880-5f18-11eb-9f58-faa9af2b0e5b.jpg)

2021-01-25 13:22 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
That's how it works now. Was only mentioning it because i.e. if you run this through the HTML validator the markup won't pass since there are custom elements within the table native elements.

2021-01-25 13:24 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
@chavlji Though now I'm questioning why even have custom elements instead of these native elements. What's the value for us using that, instead of only having a custom table element wrap the native markup...

2021-01-25 13:28 UTC, chavlji commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
True! 😄 

Some custom styling might be the only good reason. So Zen-UI defines table-border, row bottom border,...

2021-01-25 13:30 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
The custom styling would be part of the `ZenTable` custom component.

2021-01-25 13:36 UTC, chavlji commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
So you would end up with sth like this:
```
<zen-table>
  <tr>
      <td>
        <zen-status-presenter>
      </td>
      <td>
        <zen-title-presenter>
      </td>
  </tr>
</zen-table>
```
To me it looks great!

2021-01-25 13:38 UTC, leferreyra commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
I would say the reason is Control. The same reason why you don't just give a `?query=` param on an API so the user can input custom SQL in there, you want to control how the user access data. In this case, you want to control how the user uses the table component and its children.

2021-01-25 13:50 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
Makes sense yeah. This way we enforce that the only way to use this component is with the following custom components:
```
<zen-table>
  <zen-table-row slot="header">
  </zen-table-row>
  <zen-table-row>
  </zen-table-row>
  ...
</zen-table>
```
And we build whatever we build in the component.

2021-01-25 14:01 UTC, mplesec commented on src/components/zen-table-cell/zen-table-cell.tsx
> +        <td>
![Screenshot 2021-01-25 at 15 01 48](https://user-images.githubusercontent.com/9392804/105715737-410d9980-5f1e-11eb-8bad-25bcf88474c6.png)

2021-01-25 14:44 UTC, mplesec commented
Updated what we discussed and added some basics styles, looks like this now:
![Screenshot 2021-01-25 at 15 43 17](https://user-images.githubusercontent.com/9392804/105720763-17f00780-5f24-11eb-9bad-7b1d026ec86b.png)

2021-01-26 13:26 UTC, f-jauregui approved these changes
Good work!

2021-01-26 14:38 UTC, chavlji approved these changes
Great job! 👍🏻

2021-01-26 14:38 UTC, chavlji commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
When you wouldn't want that? You always want the host to take up the whole available space?
Besides you can always override that by appending styles to `<zen-table>`.

2021-01-26 14:38 UTC, chavlji commented on src/components/zen-table/zen-table.stories.mdx
> +      <zen-table-row slot="header">
I really don't like these long names... it totally blurs the point. It will get even worse when you have some additional attrs on these elements:

![Screenshot 2021-01-26 at 15 32 09](https://user-images.githubusercontent.com/5729421/105859159-7e405d00-5fec-11eb-8b48-871abcc8c242.jpg)

I know that usually won't look that bad due to the framework's loops, but still...

2021-01-26 14:38 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.css
> +:host {
This should be a scss file?

2021-01-26 14:56 UTC, f-jauregui commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
> When you wouldn't want that? You always want the host to take up the whole available space?

Agree. And a container element defines box size.

> Besides you can always override that by appending styles to <zen-table>.

If I'm not wrong, we talked about this several times. This is a pattern that we want to avoid, whenever possible.

2021-01-26 15:05 UTC, mplesec commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
There are use cases where you want it to take up the whole space and adapt the cell heights accordingly, and then you'd want the table to take up as much space as necessary, i.e. when resizing the columns.

2021-01-26 15:06 UTC, mplesec commented on src/components/zen-table-row/zen-table-row.css
> +:host {
Oh yeah, I needed a variable before.

2021-01-26 15:06 UTC, chavlji commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
Yeah, but last time we've said we won't do layout components. Bottom line: layout is on the app's side and component shouldn't have to do anything with that.
If you can do it some other way than using styles it's fine...

2021-01-26 15:08 UTC, mplesec commented on src/components/zen-table/zen-table.stories.mdx
> +      <zen-table-row slot="header">
It's a matter of preference I guess. We asked the consumers, @leferreyra expressed a preference for the full name.

2021-01-26 15:12 UTC, leferreyra commented on src/components/zen-table/zen-table.stories.mdx
> +      <zen-table-row slot="header">
full names all day baby

2021-01-26 15:16 UTC, f-jauregui requested changes

2021-01-26 15:16 UTC, f-jauregui commented on src/components/zen-table-header-cell/test/zen-table-header-cell.spec.tsx
> +});
Tests will be added in this PR?

2021-01-26 15:17 UTC, mplesec commented on src/components/zen-table-header-cell/test/zen-table-header-cell.spec.tsx
> +});
Later, I'd like to finish the minimum components and props first. I'll be adding the stories though (might just add VRT as well with that).

2021-01-26 15:34 UTC, mplesec commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
Ah ok. So it would make sense then to use `width: 100%` as the default?

2021-01-26 15:41 UTC, chavlji commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
Yep. It seems the most useful. If the app needs some other layout, it can change it without a prop.

2021-01-26 15:43 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.css
> +:host {
So it's standardized. Are there any cons against using css in scss files?

2021-01-26 16:21 UTC, mplesec commented on src/components/zen-table-row/zen-table-row.css
> +:host {
None, didn't know this was a rule. I assumed since the scaffolding creates a css file that we use scss only when we need some functionality of it.

2021-01-26 16:29 UTC, mplesec commented on src/components/zen-table/zen-table.tsx
> +  @Prop() readonly fullWidth: boolean = false;
Makes sense, removed the prop

2021-01-26 18:03 UTC, f-jauregui approved these changes

2021-01-27 09:21 UTC, merged