PLAT-882: Fix cross browser issues
reciprocity/zen-ui pull request #123
Opened 2021-01-25 21:36 UTC by f-jauregui

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-882)

#### Description
All detected cross browser and OS component issues in storybook were solved in this little PR.
This also includes a change in the zen-checkbox box element that might solve [this issue](https://reciprocitylabs.atlassian.net/browse/BAN-97), by unifying all browsers checkbox with an SVG and added the **indeterminate** variant.

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-26 16:28 UTC, mplesec approved these changes
Good work 👍

2021-01-26 16:28 UTC, mplesec commented on src/components/zen-button/zen-button.scss
> +  width: -moz-fit-content;
Might make sense to just add https://github.com/browserslist/browserslist 😅 Fewer of these one off fixes

2021-01-26 16:28 UTC, mplesec commented on src/components/zen-checkbox/zen-checkbox.scss
> +      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='9' viewBox='0 0 12 9'%3E%3Cpath d='M10.2188 0.445312L4.05469 6.63281L1.78125 4.35938C1.734
Hm, why these svgs?

2021-01-26 18:05 UTC, f-jauregui commented on src/components/zen-checkbox/zen-checkbox.scss
> +      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='9' viewBox='0 0 12 9'%3E%3Cpath d='M10.2188 0.445312L4.05469 6.63281L1.78125 4.35938C1.734
Depending the browser and also the OS these checks "icons" and boxes are different. In this way we create an homogeneous design across all browsers and OS.
SVG is the lightest way to do this. Bootstrap 5 for example is taking this approach: https://getbootstrap.com/docs/5.0/forms/checks-radios/

2021-01-27 14:44 UTC, chavlji requested changes
Great job! Please just restore the tooltip's max-width.

2021-01-27 14:44 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> -  max-width: 11rem;
Why should this be removed? Long tooltips should be broken into multiple lines. This looks strange:
![Screenshot 2021-01-27 at 15 38 18](https://user-images.githubusercontent.com/5729421/106006692-ca0b0900-60b5-11eb-8af0-35276e37f7f9.jpg)

2021-01-27 14:44 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.scss
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='9' viewBox='0 0 12 9' fill='none'%3E%3Cpath d='M10.2188 0.445312L4.05469 6.63281L1.78125 4.3
Could we use standard fa icons for this purpose? Just for the sake of standardization.
We've already used fa svgs on steps component, notifications,...
You can add a new task for this that will be done when we have the icon task ready.

2021-01-28 11:49 UTC, chavlji approved these changes

2021-01-28 11:49 UTC, merged