PLAT-1013: ZenTable unit tests
reciprocity/zen-ui pull request #130
Opened 2021-01-28 13:04 UTC by mplesec

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1013)

#### Description
Some simple unit tests for these components since there's not much else to test yet.

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-28 13:33 UTC, chavlji requested changes

2021-01-28 13:33 UTC, chavlji commented on src/components/zen-table-cell/test/zen-table-cell.spec.tsx
> +    expect(page.root).toEqualHtml(`
I'm not sure regarding these snapshot tests... they're not very useful and are very hard to maintain.
We've deleted them from all other components.

2021-01-28 13:45 UTC, mplesec commented on src/components/zen-table-cell/test/zen-table-cell.spec.tsx
> +    expect(page.root).toEqualHtml(`
I don't know about other component, but in these components they're necessary to test that the slot content is passed in as expected, and to check that an attribute was applied correctly. AFAIK there's no other way to determine correctness than this (apart from visual tests, but those are mean't to mostly test how components look).

2021-01-28 15:11 UTC, chavlji commented on src/components/zen-table-cell/test/zen-table-cell.spec.tsx
> +    expect(page.root).toEqualHtml(`
Aha ok. Agree to that. I think @f-jauregui also had a case where he wanted to check if slot gets rendered.

2021-01-28 15:11 UTC, chavlji approved these changes

2021-01-28 15:55 UTC, merged

2021-01-28 16:06 UTC, f-jauregui commented on src/components/zen-table-cell/test/zen-table-cell.spec.tsx
> +    expect(page.root).toEqualHtml(`
It's merged, but 🤷‍♂️ 

Shadow DOM of the component can be accessed by the `page.root.shadowRoot` object. 

To check if the slot was rendered:

```js
expect(page.root.shadowRoot.querySelector('slot')).toBeTruthy();
```

To check if some content was applied to a named slot:

```js
expect(page.root.querySelector('[slot="namedSlot"]')).toBeTruthy();
```

And so on...

2021-01-29 12:41 UTC, mplesec commented on src/components/zen-table-cell/test/zen-table-cell.spec.tsx
> +    expect(page.root).toEqualHtml(`
Addressed in https://github.com/reciprocity/zen-ui/pull/135