BAN-40: Create zen-button component
reciprocity/zen-ui pull request #14
Opened 2020-11-23 20:51 UTC by f-jauregui

**Updates in this PR:**
- New Stencil zen-button created with:
  - Primary, secondary, tertiary and destructive variants
  - Disabled state ready
  - Loading state ready

- Stories to show variants and properties of the component

2020-11-25 10:06 UTC, chavlji requested changes
Looks and works nice! Just a few remarks for making it more zen-ui-comply :)

2020-11-25 10:35 UTC, f-jauregui commented on src/components/zen-button/zen-button.scss
> +  line-height: 20px;
Why em instead of rem?

2020-11-25 11:29 UTC, f-jauregui commented on src/components/zen-button/zen-button.stories.ts
> +  component: 'zen-button',
zen-button regarding Stencil docs

2020-11-25 11:32 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +  line-height: 20px;
Line height should always be set in accordance with the actual font size. Usually 1.2em.

2020-11-26 13:34 UTC, chavlji requested changes
A few minor corrections...

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.tsx
> +  @Prop() loading?: boolean;
Please add default values, so that docs look nice.

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +@import "../../zen-styles/mixins/buttons.scss";
This mixin isn't meant to be used outside zen-button. Please move the mixin directly into zen-button/zen-button.scss or if you want it more granular, create a new file zen-button/mixins.scss.

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +  font-weight: 400;
You can drop this as 400 will be the default weight.

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +  -webkit-user-select: none;
We'll have auto prefixer, so you can remove these.

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +  border-radius: .2rem;
Extract this into global var $button-radius

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +  transition: color .2s ease-in-out, background-color .2s ease-in-out, border-color .2s ease-in-out, box-shadow .2s ease-in-out;
Please use global var $transition-color

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +    cursor: pointer;
Move this to `.btn` and in `&.disabled` change it back to `cursor:default`

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +  border-color: $color-white;
Remove. Transparent from .btn is ok

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +    cursor: pointer;
Remove

2020-11-26 13:34 UTC, chavlji commented on src/components/zen-button/zen-button.scss
> +.btn-destructive {
Please move this one after primary, because their implementation is very similar

2020-11-26 13:34 UTC, chavlji commented on src/zen-styles/variables.scss
> +$text-md: 1.4rem !default;
Move after text-lg

2020-11-26 13:34 UTC, chavlji commented on src/zen-styles/mixins/buttons.scss
> +@mixin button-variant($color, $background, $border, $hover, $focus, $active) {
Nice!

2020-11-26 13:34 UTC, chavlji commented on src/zen-styles/mixins/buttons.scss
> +    cursor: pointer;
Remove. Should be in .btn

2020-11-26 14:27 UTC, chavlji approved these changes
Great!

2020-11-26 14:27 UTC, merged