PLAT-1016 : POC avatar group
reciprocity/zen-ui pull request #148
Opened 2021-02-03 13:32 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1016)

#### Description

Just a poc for avatar group. Please dont go into to much detail regarding review. Just if you see mayor issues with it, conceptual. Will split this in couple of prs.

If you think there is not so much to change, i can merge this one aswell. :)

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-03 15:28 UTC, chavlji requested changes
Great job! 🏆 

A few minor stuff to change...

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/test/zen-avatar-tooltip.spec.tsx
> +describe('zen-avatar-tooltip', () => {
Don't do snapshot tests. They're impossible to maintain. If nothing else, you can test is shadow dom is there and that's it.

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +          class={{ 'main-avatar-icon': true, animation: this.showAnimation }}
Don't turn props into classes. Use `{reflect: true}` and selector `host([animateion]) ...`

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/test/zen-avatar-tooltip.spec.tsx
> +});
Missing test for `getFirstUserValue()`

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +  getFirstUserValue(property: string): string {
Shortened to:
`return this.users[0] ? this.users[0][property] : '';`

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +  @Prop() readonly showAnimation: boolean = false;
Please rename to `animate`.

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +          user-name={this.users.length == 1 ? this.getFirstUserValue('userName') : '+' + this.users.length}
Please change this into a separate function. It will be easier to read and test.
Same for `background` and `color`.

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.scss
> +.tooltip {
Remove this and use tooltip's prop `maxHeight` instead. It also takes care of some other stuff (currently user can't scroll if you try it in storybook).

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +        <zen-tooltip class="column" variant="light" show-delay="0">
Why do you need class `column` here? Would it be any different without it?

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +            <div>
Why this wrapping div?

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +                  class="avatar"
Please remove and use selector `[zen-avatar-icon]` in css

2021-02-03 15:28 UTC, chavlji commented on src/componets-smart/zen-avatar-group/zen-avatar-group.scss
> +:host(.container) {
Why this class? Could you just move it directly into `:host` since this class is a static thing? If so, please also remove the class from the tsx.

2021-02-03 15:28 UTC, chavlji commented on src/componets-smart/zen-avatar-group/test/zen-avatar-group.spec.tsx
> +  it('renders', async () => {
Don't do snapshot tests.

2021-02-03 15:28 UTC, chavlji commented on src/componets-smart/zen-avatar-group/zen-avatar-group.tsx
> +  /** User to display  */
Better: Max number of users to display

2021-02-03 15:28 UTC, chavlji commented on src/componets-smart/zen-avatar-group/zen-avatar-group.tsx
> +  /** Users  */
Better: Array of user's data

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.scss
> +  transition: transform 0.3s;
Add new var for this value to `variables.scss`

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +export class ZenAvatarTooltip {
Name of the component isn't ok. Should be named `zen-avatar`, because it's not just a tooltip but `zen-icon` + `zen-tooltip` instead.

2021-02-03 15:28 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> -  max-width: 11rem;
Don't remove this. We don't want tooltips that stretch through the whole viewport. If the content of the tooltip is too long, the text should break.

2021-02-04 12:59 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/test/zen-avatar-tooltip.spec.tsx
> +describe('zen-avatar-tooltip', () => {
removed

2021-02-04 13:10 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +  getFirstUserValue(property: string): string {
Done

2021-02-04 13:10 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +          class={{ 'main-avatar-icon': true, animation: this.showAnimation }}
Done

2021-02-04 13:11 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +  @Prop() readonly showAnimation: boolean = false;
Renamed. Animate name is already taken.

2021-02-04 13:11 UTC, mihaelpalfi commented on src/componets-smart/zen-avatar-group/zen-avatar-group.tsx
> +  /** User to display  */
Done

2021-02-04 13:12 UTC, mihaelpalfi commented on src/componets-smart/zen-avatar-group/zen-avatar-group.tsx
> +  /** Users  */
Done

2021-02-04 13:14 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.scss
> +  transition: transform 0.3s;
done

2021-02-04 13:14 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +export class ZenAvatarTooltip {
done

2021-02-04 13:36 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> -  max-width: 11rem;
done

2021-02-05 09:07 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +          user-name={this.users.length == 1 ? this.getFirstUserValue('userName') : '+' + this.users.length}
Done

2021-02-05 09:09 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +            <div>
Because you can add only one child to slot.

2021-02-05 09:10 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +        <zen-tooltip class="column" variant="light" show-delay="0">
You are right. removed.

2021-02-05 09:10 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.scss
> +.tooltip {
Done

2021-02-05 09:15 UTC, mihaelpalfi commented on src/componets-smart/zen-avatar-group/zen-avatar-group.scss
> +:host(.container) {
Done

2021-02-05 09:19 UTC, mihaelpalfi commented on src/componets-smart/zen-avatar-group/test/zen-avatar-group.spec.tsx
> +  it('renders', async () => {
removed

2021-02-05 09:20 UTC, mihaelpalfi commented on src/components/zen-avatar-tooltip/zen-avatar-tooltip.tsx
> +                  class="avatar"
Dosent work for me. :(

2021-02-05 10:20 UTC, chavlji approved these changes

2021-02-05 11:09 UTC, merged