PLAT-1040: Update notification styles
reciprocity/zen-ui pull request #159
Opened 2021-02-10 07:43 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1040)

#### Description
As per JIRA ticket

![image](https://user-images.githubusercontent.com/59830865/107479868-fcb80580-6b7b-11eb-9be8-d21dbd2cc3e3.png)

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-10 14:12 UTC, f-jauregui approved these changes
I would just change the Icon usage. Otherwise, fantastic job Mihael. Those notifications look great!

2021-02-10 14:12 UTC, f-jauregui commented on src/components/zen-notification/zen-notification.tsx
> +            <div class={icon}>{getIcon(this.variant)}</div>
You can use `<zen-icon>` now to achieve this.
In line 73 can be also changed to use `<zen-icon>`.

2021-02-10 14:15 UTC, mplesec approved these changes
Awesome 👍

Only one nitpick, these should be vertically aligned as well:
![Screenshot 2021-02-10 at 15 15 08](https://user-images.githubusercontent.com/9392804/107521446-d82b5000-6bb2-11eb-993f-27e20f420c4e.png)

2021-02-11 08:28 UTC, chavlji requested changes
Nice! Though styling seems a bit off according to designs (designs are on right). Use [perfect pixel](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en) to match it 100%.

![Screenshot 2021-02-11 at 09 22 08](https://user-images.githubusercontent.com/5729421/107614788-47548300-6c4b-11eb-8a32-3c8f3ab65965.jpg)

![Screenshot 2021-02-11 at 09 21 53](https://user-images.githubusercontent.com/5729421/107614804-4de2fa80-6c4b-11eb-82a1-29e2231a37f3.jpg)

And one more thing: please remove prop `message` and replace it with the default slot. It's way more natural.

2021-02-11 08:28 UTC, chavlji commented on src/components/zen-notification/functions.ts
> +import { faInfoCircle, faCheckCircle, faExclamationTriangle, faTimesHexagon } from '@fortawesome/pro-light-svg-icons';
Please rename this file to `helpers.ts`

2021-02-11 08:28 UTC, chavlji commented on src/components/zen-notification/zen-notification.tsx
> +            <div class={icon}>{getIcon(this.variant)}</div>
True 👍

2021-02-11 08:54 UTC, mihaelpalfi commented on src/components/zen-notification/zen-notification.tsx
> +            <div class={icon}>{getIcon(this.variant)}</div>
Done

2021-02-11 08:56 UTC, mihaelpalfi commented on src/components/zen-notification/functions.ts
> +import { faInfoCircle, faCheckCircle, faExclamationTriangle, faTimesHexagon } from '@fortawesome/pro-light-svg-icons';
Done

2021-02-12 09:19 UTC, chavlji approved these changes

2021-02-12 09:19 UTC, merged