POC for popover component
reciprocity/zen-ui pull request #165
Opened 2021-02-11 18:36 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/)

#### Description
As per JIRA ticket

1. Dont really see benefits of this popper library. Tried a lot of things. But positioning still worked funny for me. 
2. Tried also with tippy library. That has a lot more options and has opening functionality out of the box. But had also issue with close on click outside of popover window.
3. Also added a story for filtering component. It was quite hard. Please all of you try to build a complete bigger component and you will see what am i talking about.

Should i rather reuse tooltip functionality but would need help with closing popover on clicking outside off it.

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-15 05:43 UTC, f-jauregui reviewed
I like the direction of this POC. Great job, Mihael! 🤙 
IMO is a good start. Maybe for the first iteration should have some event listener in case you want to close it the popover from the "target" or some button in the content inside the popover.
Would like to see what @chavlji and @mplesec think about this.

2021-02-15 11:36 UTC, chavlji requested changes
Very nice! I've added a few comments, but most of them can be changed in a separate PRs.

2021-02-15 11:36 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +      console.error('No target element specified for the target slot!');
Imo passing target element as `prev` element is better option, because if you insist in wrapping target with your component, you ruin dom's hierarchy. I know that at least Leo would disagree with me, so we should maybe vote on this.

But in the mean time, if target slot isn't fulfilled, proclaim prev element as the target element. It's non-destructive way to support both functionalities.

2021-02-15 11:36 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +    const instance = createPopper(targetSlotEl, defaultSlotEl, {
promote this to private class variable, because we might need it somewehere else later.

2021-02-15 11:36 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +  show(instance, element: HTMLElement): void {
when `instance` is private class var there's no need to pass it as a param

2021-02-15 11:36 UTC, chavlji commented on src/components/zen-popover/zen-popover.stories.mdx
> +### 2. Story for filters component
Please add a story with scrollable content so we can check that popper is positioned to opposite side if there's not enough space on original popup side.

2021-02-15 11:36 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +    element.style.display = 'block';
Add a ticket to improve animation.

2021-02-15 11:36 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +  @Prop() readonly offset: Offsets = { x: 0, y: 8 };
add props:
- `triggeringEvents`: [`click`, `focus`, `hover`]
- `hoverDelay`: number - timeout for how much time mouse needs to stay in one point
- `hideDelay`: number
- `visible`: `boolean | undefined` - if user passes this prop (isn't undefined) it should force show/hide popover.

All of those can be done in a separate PR.

2021-02-15 14:46 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.tsx
> +      console.error('No target element specified for the target slot!');
Done

2021-02-15 14:50 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.tsx
> +    const instance = createPopper(targetSlotEl, defaultSlotEl, {
Done

2021-02-15 14:50 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.tsx
> +  show(instance, element: HTMLElement): void {
Done

2021-02-16 05:27 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.stories.mdx
> +### 2. Story for filters component
Added

2021-02-16 05:48 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.tsx
> +    element.style.display = 'block';
Added

2021-02-16 05:48 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.tsx
> +  @Prop() readonly offset: Offsets = { x: 0, y: 8 };
Added

2021-02-16 09:00 UTC, chavlji commented
> I like the direction of this POC. Great job, Mihael! 🤙
> IMO is a good start. Maybe for the first iteration should have some event listener in case you want to close it the popover from the "target" or some button in the content inside the popover.
> Would like to see what @chavlji and @mplesec think about this.

I agree, but prop `visible: boolean` would be better for this purpose instead of an event.

2021-02-16 09:24 UTC, chavlji requested changes
One minor change, please.
Unit tests will be written in a different pr?

2021-02-16 09:24 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +    window.addEventListener('click', event => {
This listener should be added on popover show and removed on hide/destroy.

2021-02-16 09:24 UTC, chavlji commented on src/components/zen-popover/zen-popover.tsx
> +      console.error('No target element specified for the target slot!');
Nice! It might be a good idea to make a story about that?

2021-02-16 16:04 UTC, mihaelpalfi commented on src/components/zen-popover/zen-popover.tsx
> +    window.addEventListener('click', event => {
Done

2021-02-17 13:17 UTC, chavlji approved these changes

2021-02-17 13:17 UTC, merged