PLAT-1149: Components registry issue fix
reciprocity/zen-ui pull request #167
Opened 2021-02-11 20:44 UTC by f-jauregui

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-15 07:12 UTC, mihaelpalfi approved these changes
Good work Fermin! Quite a lot of changes.

2021-02-15 07:52 UTC, mplesec requested changes
Awesome job on all this 👍 I reviewed the config and skimmed through the rest of the changes. Left a couple of questions.

Also, I'm wondering what's with the visual tests here?
![Screenshot 2021-02-15 at 08 50 54](https://user-images.githubusercontent.com/9392804/107919060-0621e300-6f6b-11eb-93bb-a69b5edabe74.png)

2021-02-15 07:52 UTC, mplesec commented on src/components/zen-space/zen-space.stories.mdx
> +  sb-zen-space {
Hm referencing the tag directly? Maybe in the future we should use a css class for such cases instead 😅

2021-02-15 07:52 UTC, mplesec commented on src/stories/components/color-swatch-group/readme.md
> -## Dependencies
How come all of these are getting removed?

2021-02-15 07:52 UTC, mplesec commented on src/components/zen-modal/zen-modal.tsx
> +                      <ZenButton class="btn-cancel" variant="secondary" onClick={() => this.onCancelClicked()}>
Why the different case?

2021-02-16 22:56 UTC, f-jauregui commented on src/stories/components/color-swatch-group/readme.md
> -## Dependencies
This file wasn't touched since we added the new doc style with MDX, and as I updated the color-swatch group with the new prefix this is automatically removed.

2021-02-16 22:56 UTC, f-jauregui commented on src/components/zen-modal/zen-modal.tsx
> +                      <ZenButton class="btn-cancel" variant="secondary" onClick={() => this.onCancelClicked()}>
This is the only way JSX has to place a dynamic tag.

2021-02-16 23:00 UTC, f-jauregui commented on src/components/zen-space/zen-space.stories.mdx
> +  sb-zen-space {
Just updating some existing CSS inside the story. If we need to change this in the future there's no problem. Just wanted to keep this PR as focused as possible since is a big one.

2021-02-16 23:05 UTC, f-jauregui commented
@mplesec already updated all VRT. Thanks for that review! 💯

2021-02-17 13:04 UTC, mplesec reviewed
@f-jauregui a lot of these look very different, is this expected?
![Screenshot 2021-02-17 at 14 04 28](https://user-images.githubusercontent.com/9392804/108208252-15e72600-7129-11eb-88bc-873f96e20cf4.png)

2021-02-18 09:58 UTC, chavlji approved these changes
Great job Fermin! 🏅 Works as expected!

2021-02-18 09:58 UTC, chavlji commented on src/components/zen-avatar-group/zen-avatar-group.stories.mdx
> -      <zen-avatar-group id="avatar-group-control" ...="${spreadArgs(args, argTypes)}" />
I love the short prefix!

2021-02-18 11:06 UTC, mplesec approved these changes

2021-02-18 14:47 UTC, merged