PLAT-1195: Fix number of avatar icons
reciprocity/zen-ui pull request #169
Opened 2021-02-12 08:59 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1195)

#### Description
As per JIRA ticket

![image](https://user-images.githubusercontent.com/59830865/107748169-ec895d00-6d18-11eb-8bf4-d55b434b1ff4.png)

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-12 09:20 UTC, mplesec requested changes

2021-02-12 09:20 UTC, mplesec commented on src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
> +    expect(page.root.shadowRoot.querySelectorAll('zen-avatar').length).toEqual(4);
Hm, this doesn't really check it they're inside the tooltip though

2021-02-12 09:20 UTC, mplesec commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
This won't correctly handle the case where if you have i.e. 8 users to display and the `displayMax` is either 6 or 7. In both cases it'll render 6 users and 2 in the tooltip.

2021-02-12 09:22 UTC, mplesec commented
@mihaelpalfi also found a related issue (probably storybook). When changing the value of `displayMax` property the rendered items in the tooltip do not reflect the number specified in the icon.
![Uploading Screenshot 2021-02-12 at 10.16.04.png…]()

2021-02-12 11:25 UTC, mihaelpalfi commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
Did you test it? Becouse for me it does. This was the point of this fix. That if you have 8 users and you set show 7 icons the 7 one has +2 and 7,8 user in the tooltip.

2021-02-12 11:26 UTC, mihaelpalfi commented on src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
> +    expect(page.root.shadowRoot.querySelectorAll('zen-avatar').length).toEqual(4);
This is the issue that i mentioned. Cant really get to the tooltip component with jest.

2021-02-12 11:29 UTC, mihaelpalfi commented
> @mihaelpalfi also found a related issue (probably storybook). When changing the value of `displayMax` property the rendered items in the tooltip do not reflect the number specified in the icon.

I can see a scroller.

![image](https://user-images.githubusercontent.com/59830865/107762815-e356bb00-6d2d-11eb-8c25-0547b580418a.png)

2021-02-12 13:10 UTC, mplesec commented
> > Mihael Palfi also found a related issue (probably storybook). When changing the value of `displayMax` property the rendered items in the tooltip do not reflect the number specified in the icon.
> 
> I can see a scroller. And all 6 users in it.

Interesting, this is what happens when I try this:

https://user-images.githubusercontent.com/9392804/107772051-f7091e00-6d3b-11eb-9430-a90178ab8f53.mov

Browser: Chrome 88.0.4324.150 (x86_64)

2021-02-12 13:14 UTC, mplesec commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
Oh, I didn't understand that. In that case, seems confusing to do that, since if the consumer specifies 7 they would expect 7 of them displayed.

2021-02-12 13:29 UTC, mplesec commented on src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
> +    expect(page.root.shadowRoot.querySelectorAll('zen-avatar').length).toEqual(4);
Wouldn't the same approach as on L64 work?
https://github.com/reciprocity/zen-ui/blob/3a565df7253c6ef3b9717afee623cf1d438e0536/src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx#L64

2021-02-13 17:41 UTC, mihaelpalfi commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
This is a good one. Thinked about it once again and changed the implementation.  I think that QA is wrong. Based on the functional wireframes if we want to see 7 icons and you have 8. We display 6 avatars and on with +2. So together there are 7 icons displayed.

Now it should be correct.

![image](https://user-images.githubusercontent.com/59830865/107856799-fb603480-6e2a-11eb-83c3-df11d6315a0b.png)

2021-02-13 17:54 UTC, mihaelpalfi commented on src/components/zen-avatar-group/test/zen-avatar-group.spec.tsx
> +    expect(page.root.shadowRoot.querySelectorAll('zen-avatar').length).toEqual(4);
Yes you are right. Changed.

2021-02-13 17:59 UTC, mihaelpalfi commented
> 
> Interesting, this is what happens when I try this:
> 
Lets try to reproduce this together.

2021-02-15 05:20 UTC, f-jauregui commented
> > > Mihael Palfi also found a related issue (probably storybook). When changing the value of `displayMax` property the rendered items in the tooltip do not reflect the number specified in the icon.
> > 
> > 
> > I can see a scroller. And all 6 users in it.
> 
> Interesting, this is what happens when I try this:
> 
>  Screen.Recording.2021-02-12.at.14.08.39.mov 
> Browser: Chrome 88.0.4324.150 (x86_64)

Experiencing same thing. Tested in Chrome, Safari and Firefox.

2021-02-15 07:07 UTC, mihaelpalfi commented
> > > > Mihael Palfi also found a related issue (probably storybook). When changing the value of `displayMax` property the rendered items in the tooltip do not reflect the number specified in the icon.
> > > 
> > > 
> > > I can see a scroller. And all 6 users in it.
> > 
> > 
> > Interesting, this is what happens when I try this:
> > Screen.Recording.2021-02-12.at.14.08.39.mov
> > Browser: Chrome 88.0.4324.150 (x86_64)
> 
> Experiencing same thing. Tested in Chrome, Safari and Firefox.

If you guys are talking about that you cant move the mouse inside the tooltip. Its again the issue because of the fix that tooltip dosent hide. I fixed the issue in another pr.

2021-02-15 07:41 UTC, mplesec commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
I'd sooner argue we need to challenge the functional spec then. This is imo unexpected behavior for whoever will be using it.

If we do decide to keep it like this, I think we should change the prop description to reflect this. Currently it's `Max number of users to display`, which gives the wrong impression of what will happen. And maybe add a story for this behavior as well.

Also, in the description it says 5 icons is the max, but in this PR it's 8.

2021-02-15 09:33 UTC, chavlji commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
The current implementation is what I'd expect. Imo it's working correctly. All misunderstandings here orignates from prop name and description. Should be:
`maxIcons` - `Max number of icons to display`

2021-02-15 09:35 UTC, chavlji requested changes
Just rename the prop please and that's it.

2021-02-15 09:46 UTC, mihaelpalfi commented on src/components/zen-avatar-group/zen-avatar-group.tsx
> +    }
Updated param name and added description to story.

2021-02-15 09:52 UTC, mplesec approved these changes

2021-02-15 09:57 UTC, chavlji approved these changes

2021-02-15 09:57 UTC, merged