PLAT-1224: Fix tooltip padding
reciprocity/zen-ui pull request #175
Opened 2021-02-15 13:41 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1224)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-15 15:55 UTC, chavlji requested changes
Nice! It all looks good, I just have concerns regarding the convenience of such highly customizable tooltips.

2021-02-15 15:55 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +            <zen-space padding="lg">
Imo both `zen-space` and `zen-text` should be a part of default content... It's very tidious to have to repeat this throughout the app all the time for each small tooltip.
Just make default slot content of `zen-text` then.
For more custom cases we can have a slot named `content`. If slot `content` is fulfilled, we wouldn't render `zen-space` and `zen-text` but just this slot instead.
That would provide high standardization along with high customization when needed.

2021-02-16 05:52 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +            <zen-space padding="lg">
Do we do this for the tooltip or in popover? Why do you think we  have to remove the tooltip?

2021-02-16 08:56 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +            <zen-space padding="lg">
In tooltip. Popover's content is so specific and custom that it's expected users should provide padding. But when it comes to tooltips, 99% of tooltips focus just on the text content and should look uniformed across the apps.

What do you mean by "remove the tooltip"? I just thought we should use the popover component for the tooltip container when it's ready. This way we don't have to calculate its position manually.

2021-02-16 12:12 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +            <zen-space padding="lg">
Updated that zen space wrappes default slot content. And added slot content for special contents.

2021-02-16 12:43 UTC, chavlji approved these changes

2021-02-16 12:43 UTC, merged