PLAT-1288: Fix popover and calendar tag prefix
reciprocity/zen-ui pull request #187
Opened 2021-02-18 15:04 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1288)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-18 15:29 UTC, f-jauregui requested changes
Just those little changes in the component main files.

2021-02-18 15:29 UTC, f-jauregui commented on src/components/zen-date-picker/zen-date-picker.tsx
> +        </sb-zen-input>
Inside the component is a bit different than the stories.
We need to create the dynamic tags so we support any incoming prefix, not just `sb`.
In order to do that:

```js
const ZenInput = applyPrefix('zen-input', this.hostElement);
const ZenSpace = applyPrefix('zen-space', this.hostElement);
const ZenIcon = applyPrefix('zen-icon', this.hostElement);

<ZenInput placeholder={this.placeholder} value={this.formattedDate}>
  <ZenSpace padding="md none md md" slot="leadingSlot">
    <ZenIcon icon={faCalendarAlt}></ZenIcon>
  </ZenSpace>
</ZenInput>
```

Do that for this and the popover component.

2021-02-18 18:02 UTC, mihaelpalfi commented on src/components/zen-date-picker/zen-date-picker.tsx
> +        </sb-zen-input>
Done.

2021-02-18 20:06 UTC, chavlji commented
Was broken before. This pr fixes it!

2021-02-18 20:07 UTC, chavlji approved these changes
Was broken before. This pr fixes it!

2021-02-18 20:26 UTC, chavlji approved these changes

2021-02-19 07:59 UTC, chavlji commented
@f-jauregui I'm merging this because it's blocking me. Please check it out and we can open a new pr if there are any flaws.

2021-02-19 07:59 UTC, merged