PLAT-1265: Add icon padding
reciprocity/zen-ui pull request #190
Opened 2021-02-19 10:46 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1265)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-19 14:42 UTC, chavlji requested changes

2021-02-19 14:42 UTC, chavlji commented on src/components/zen-icon/test/zen-icon.spec.tsx
> +  it.each(['xs', 'sm', 'md', 'lg', 'xl'])('should correctly apply padding (padding: %s)', async (padding: string) => {
Testing one single prop eg. `sm` and one composed prop eg. `sm none` should be enough.

2021-02-19 14:42 UTC, chavlji commented on src/components/helpers/helpers.ts
> +  let paddingClasses: Record<string, unknown> = {};
Test for this function should be moved from `zen-space.spec.ts - should correctly parse padding shorthands` into `helpers.spec.ts`

2021-02-19 14:42 UTC, chavlji commented on src/components/zen-icon/zen-icon.tsx
> +  @Prop() readonly padding: Size | None | string = 'sm';
Since this is now used in two places, please add special type `PaddingShorthands` into global `types.ts` and replace it here and in file `zen-space.tsx`.

2021-02-19 14:42 UTC, chavlji commented on .stylelintrc.json
> +  "extends": "stylelint-config-standard"
Nice! Do we now have fully working style lint?

2021-02-22 08:20 UTC, mihaelpalfi commented on src/components/helpers/helpers.ts
> +export function paddingChanged(padding: string): Record<string, unknown> {
Done

2021-02-22 08:22 UTC, mihaelpalfi commented on src/components/zen-icon/test/zen-icon.spec.tsx
> +  it.each(['xs', 'sm', 'md', 'lg', 'xl'])('should correctly apply padding (padding: %s)', async (padding: string) => {
Done

2021-02-22 08:29 UTC, mihaelpalfi commented on src/components/zen-icon/zen-icon.tsx
> +  @Prop() readonly padding: Size | None | string = 'sm';
Replaced.

2021-02-22 08:30 UTC, mihaelpalfi commented on .stylelintrc.json
> +  "extends": "stylelint-config-standard"
We should. I had to add it so style lint is picked up also in pychar.

2021-02-22 08:32 UTC, mihaelpalfi commented on src/components/helpers/helpers.ts
> +  let paddingClasses: Record<string, unknown> = {};
Where should i place this file helpers.spec.ts? Into the zen icon folder or somewhere global?

2021-02-22 09:16 UTC, chavlji requested changes

2021-02-22 09:16 UTC, chavlji commented on src/components/helpers/helpers.ts
> +  let paddingClasses: Record<string, unknown> = {};
always next to the file: `components/helpers/helpers.spec.ts`

2021-02-22 09:16 UTC, chavlji commented on src/components/zen-icon/zen-icon.stories.mdx
> +    <sb-zen-space  horizontal-align="space-evenly">
Please add labels under each icon, so user can quickly see what padding value is applied. Check `/src/components/zen-space/zen-space.stories.mdx` for example. You'll have to wrap each icon into additional `zen-space` so that label sits under icon

2021-02-22 09:16 UTC, chavlji commented on src/components/helpers/helpers.ts
> +  let paddingClasses: Record<string, unknown> = {};
always next to the file: components/helpers/helpers.spec.ts

2021-02-22 09:44 UTC, mihaelpalfi commented on src/components/helpers/helpers.ts
> +  let paddingClasses: Record<string, unknown> = {};
Done

2021-02-22 09:58 UTC, mihaelpalfi commented on src/components/zen-icon/zen-icon.stories.mdx
> +    <sb-zen-space  horizontal-align="space-evenly">
Done

2021-02-22 10:01 UTC, chavlji approved these changes

2021-02-22 10:02 UTC, merged