PLAT-1316: ZenPanel component
reciprocity/zen-ui pull request #193
Opened 2021-02-22 11:21 UTC by mplesec

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1316)

#### Description
PR adds a simple panel component. When looking up on how others did a collapse component I came across the Ant Design does it: https://ant.design/components/collapse/. And I like that approach a lot. The idea is to split the component into collapse and panel components.

Also haven't added any animations to the chevron, I guess I'll wait till that's consolidated.

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-22 11:47 UTC, chavlji commented
@mplesec I don't like this approach.

`zen-collapse` should not contain a trigger. Trigger (the thing that expands zen-collapse it) can be whatever you like (button, row, input,...). It can exist even without a trigger and can be expanded only through js.

We're already just creating a component called `zen-drawer` which is basically the same thing only animation is different (drawer slides on top, collapse pushes away existing elements).

Can you please mock this in the app for now? We'll have it ready by Wednesday.

2021-02-22 12:06 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +  @Prop() readonly header: string = 'Header';
Remove this prop and add a slot `headerContent`.

2021-02-22 12:19 UTC, mplesec commented
@chavlji A drawer isn't the same as a collapse. A drawer slides out from an edge of a container, usually the viewport itself.

2021-02-22 12:20 UTC, chavlji requested changes
On second thought, it might be useful to have such a component. We can modify it later to use the drawer component for a collapsible part.

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +  @Prop() readonly header: string = 'Header';
Remove this prop and add a slot `headerContent`.

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +  @State() hidden = true;
Rename it to `visible` because we have it like that in all other components.

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +<Meta title="Containers/Panel" component="zen-panel" argTypes={argTypes} />
Change to `In progress/Panel`

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +export class ZenPanel {
Why not `ZenCollapse`? Zen-panel is synonym to zen-card imo.

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +export const StoryText = () => {
All stories should resemble real-life designs. These stories doesn't look like design screenshot in Jira.

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.scss
> +  display: flex;
Add some padding to match the design.

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.scss
> +  // border-top: 1px solid $color-gray-200;
remove

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.scss
> +// .chevron {}
remove

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.scss
> +// .content {}
remove

2021-02-22 12:20 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +  @Prop() readonly arrow: boolean = true;
Do we have it anywhere in design without an arrow? If not, I'd remove this prop because I can't see a usecase.

2021-02-22 14:43 UTC, mplesec commented on src/components/zen-panel/zen-panel.tsx
> +  @Prop() readonly header: string = 'Header';
Updated, used just `header` for the slot name though

2021-02-22 14:43 UTC, mplesec commented on src/components/zen-panel/zen-panel.tsx
> +  @State() hidden = true;
Updated

2021-02-22 14:44 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +<Meta title="Containers/Panel" component="zen-panel" argTypes={argTypes} />
Why though? Since it's a component we'll already be using in zencomply.

2021-02-22 14:45 UTC, mplesec commented on src/components/zen-panel/zen-panel.tsx
> +export class ZenPanel {
My reasoning is that  a collapse component can have multiple panels (like the ant design implementation). Maybe we should ask the designers about this though.

2021-02-22 14:45 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +export const StoryText = () => {
What designs? 😅 There's none for this component here: https://www.figma.com/file/rWXEQiJcBXbkMY8V4NSM1d/ZenGRC-Component-Library

2021-02-22 14:45 UTC, mplesec commented on src/components/zen-panel/zen-panel.scss
> +  // border-top: 1px solid $color-gray-200;
Done

2021-02-22 14:45 UTC, mplesec commented on src/components/zen-panel/zen-panel.scss
> +// .chevron {}
Added styles for the icon

2021-02-22 14:46 UTC, mplesec commented on src/components/zen-panel/zen-panel.scss
> +// .content {}
Done

2021-02-23 06:34 UTC, mihaelpalfi commented on src/components/zen-panel/zen-panel.stories.mdx
> +export const StoryText = () => {
Didnt you Matic post and image of the collapsible component in the ticket? I see an accordion component here https://www.figma.com/file/2qna0UZ5Qtva5vDLDKd9Gy/Access-controls-exploration-%7C-Mary---Feb?node-id=692%3A27679

2021-02-23 06:49 UTC, mihaelpalfi approved these changes
Tested and it works. Missing some animations for open and close.

2021-02-23 07:54 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +<Meta title="Containers/Panel" component="zen-panel" argTypes={argTypes} />
Because it's incomplete. Still missing designs (we have nothing from designers yet), stories don't look ok, the component isn't polished in a sense of animations. And precisely for these reasons, it's highly likely it will be changed in the near future. If you're using it in the app, you take responsibility to maintain it in the future.

2021-02-23 07:55 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +export class ZenPanel {
I'll ask designers on today's meeting.

2021-02-23 08:01 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +export const StoryText = () => {
Yes, I was referring to the screenshot from the ticket. If this is the only thing we got, it should look exactly like this screenshot.

2021-02-23 10:22 UTC, chavlji commented
@mplesec shall we wait with this component for some better designs/cleaner functional specs?

2021-02-24 08:20 UTC, mplesec commented
@chavlji Yeah let's. It's not a blocker so it's fine.

2021-02-24 13:15 UTC, mihaelpalfi commented on src/components/zen-panel/zen-panel.stories.mdx
> +<Meta title="Containers/Panel" component="zen-panel" argTypes={argTypes} />
What if we put it into in progress in story book and we can polish it after?

2021-03-01 11:14 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="text">{StoryText.bind({})}</Story>
I guess content here should be left-aligned with text in header? Talk to designers if unclear. This should be solved before using in app, because adding it later will affect already made stuff in the app.

2021-03-01 11:23 UTC, chavlji requested changes
I guess there should also be some padding on the outside? Currently, there are none. Please ask designers.
![Screenshot 2021-03-01 at 12 19 03](https://user-images.githubusercontent.com/5729421/109490567-af4afc00-7a88-11eb-9efa-a757f842a748.jpg)
Paddings are crucial to be set now because we can't add them later when component is already used in the app.

2021-03-01 11:23 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="text">{StoryText.bind({})}</Story>
I guess content here should be left-aligned with text in header? Talk to designers if unclear. This should be solved before using in app, because adding it later will affect already made stuff in the app.

2021-03-01 11:23 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="divs">{StoryDivs.bind({})}</Story>
Not a very informative story. Remove it please.

2021-03-01 11:23 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 4. Panel with form element and visible by default
No need to have story for each prop. Please remove this story.

2021-03-01 11:23 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 3. Panel with form element
No need to have story for each prop. Please remove this story.

2021-03-01 11:23 UTC, chavlji commented on src/components/zen-panel/zen-panel.tsx
> +export class ZenPanel {
I still think this should be renamed to ZenCollapse. Designer were also refering to it as collapse.

2021-03-01 11:26 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 3. Panel with form element
Add some zen-text before and after this component so padding is clearly visible.

2021-03-01 11:30 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="text">{StoryText.bind({})}</Story>
On second thought... if we take their design into consideration, it might be ok as it is (toggle is left aligned with arrow). If the consumer will want padding, he can wrap content into zen-space 🤷🏻

2021-03-01 11:31 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="text">{StoryText.bind({})}</Story>
Yeah it makes more sense to leave it to the consumer

2021-03-01 11:32 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="divs">{StoryDivs.bind({})}</Story>
It shows what happens with the div, i.e. what the padding is like for the content.

2021-03-01 11:32 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 3. Panel with form element
That's what the div story is for.

2021-03-01 11:36 UTC, mplesec commented
@chavlji will talk to designers re the naming

2021-03-01 11:37 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +<Meta title="Containers/Panel" component="zen-panel" argTypes={argTypes} />
We got the info necessary, leaving it as is

2021-03-01 11:37 UTC, mplesec commented on src/components/zen-panel/zen-panel.scss
> +  display: flex;
Added

2021-03-01 11:40 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 4. Panel with form element and visible by default
Disagree, in this case it's important to show it as a story since stories showcase core behavior.

2021-03-01 11:55 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 4. Panel with form element and visible by default
What core behavior? Can it be easily achieved through controls?

2021-03-01 11:56 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="divs">{StoryDivs.bind({})}</Story>
Is div any different than any other content? Can't this be also seen in all other stories?

2021-03-01 11:56 UTC, chavlji commented
@mplesec dont' forget to ask them about default padding of this component (my topmost comment)

2021-03-01 11:59 UTC, chavlji commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 3. Panel with form element
I meant add zen-text before and after zen-panel so we see default outer padding of this whole component.
![Screenshot 2021-03-01 at 12 58 32](https://user-images.githubusercontent.com/5729421/109494285-f7205200-7a8d-11eb-8384-d409796220b0.jpg)

2021-03-03 09:04 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +  <Story name="divs">{StoryDivs.bind({})}</Story>
The div (since it has a background color) better shows where the content boundaries end.

2021-03-03 09:08 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 4. Panel with form element and visible by default
From https://storybook.js.org/docs/react/get-started/whats-a-story
> A story captures the rendered state of a UI component. Developers write multiple stories per component that describe all the “interesting” states a component can support.

It can also be achieved through controls, however for this component showing at first glance that it can start in this state makes sense.

2021-03-03 09:33 UTC, mplesec commented
@chavlji asked Shelley regarding these things. Her opinion is that the name should be ZenPanel. As for the padding, her answer was:
> No the padding isn't really defined other than what exists in terms of line height for the text boxes

And given that this is a similar case as with i.e. an input element, it makes sense that it's up to the consumer to define the space between form elements.

2021-03-03 09:34 UTC, mplesec commented on src/components/zen-panel/zen-panel.stories.mdx
> +### 3. Panel with form element
Is this within scope for these stories though?

2021-03-04 08:26 UTC, chavlji approved these changes

2021-03-04 10:38 UTC, merged