PLAT-848: POC add drawer component
reciprocity/zen-ui pull request #194
Opened 2021-02-22 15:15 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-848)

- Will add updates in separate pr
- Will add vrt in a separate pr

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-02-22 16:45 UTC, chavlji commented on src/components/zen-drawer/zen-drawer.scss
> +  padding-left: 10px;
create special selector for these two. When you do it, remove all resets from selectors below (`padding-left:0, margin-left:0`)

2021-02-23 07:47 UTC, chavlji requested changes
Why POC in the title? POC is meant to be thrown away at the end and written from scratch. We're probably aiming to merge this one, so you can remove the POC.

2021-02-23 08:24 UTC, chavlji commented
One more thing. Close button has some strange styles on focus and hover:
![Screenshot 2021-02-23 at 09 23 58](https://user-images.githubusercontent.com/5729421/108817967-f9c80680-75b8-11eb-97fb-f15c24f00697.jpg)

2021-02-23 09:13 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.scss
> +  padding-left: 10px;
Done

2021-02-23 09:16 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.tsx
> +
Done

2021-02-23 09:20 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +     <sb-zen-space padding="none" vertical="true" horizontal-align="center" padding="lg" space="lg" style="position:relative; height: 400px" >
Done

2021-02-23 09:20 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +            </sb-zen-text>
Done

2021-02-23 09:22 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +    document.querySelector('#drawer1').opened = !document.querySelector('#drawer1').opened;
done

2021-02-23 09:25 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.scss
> +  left: 0;
Done

2021-02-23 09:26 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.scss
> +}
Hmm i have it?

2021-02-23 09:26 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +<Description>{Readme}</Description>
Hmm i have it!?

2021-02-23 09:29 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +               <sb-zen-icon size="sm" id="zen-icon-element"></sb-zen-icon>
What do you mean with this. Why should the button be repositioned. This is only an example to open the drawer.

2021-02-23 09:38 UTC, mihaelpalfi commented
> One more thing. Close button has some strange styles on focus and hover:

Arent quite sure what you mean with that. But this is probably a button issue then right? We can create a ticket,

2021-02-23 10:14 UTC, chavlji commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +               <sb-zen-icon size="sm" id="zen-icon-element"></sb-zen-icon>
it is always pointing in the same direction. Buttons like this always point to the direction of closing (eg. if the position is `top` it should point upwards).
Because it's not so easy to do in each app, it might be a good idea to put this button inside the component and add prop `showCloseButton`. This way each app wouldn't need to implement it each time.

2021-02-23 10:14 UTC, chavlji commented on src/components/zen-drawer/zen-drawer.scss
> +}
my bad then, sorry

2021-02-23 13:19 UTC, mihaelpalfi commented on src/components/zen-drawer/zen-drawer.stories.mdx
> +               <sb-zen-icon size="sm" id="zen-icon-element"></sb-zen-icon>
Done

2021-02-23 15:04 UTC, chavlji commented
Great job! Works as expected.

Please add a separate ticket for this:
1. Would be cool to **emit some event on open/close**.
2. I'd say we only have to emit an event on close arrow click and let the app handle the closing... app might have decided that the drawer shouldn't be closed (due to unsaved changes) or it might need to destroy some elements on close.

2021-02-23 15:05 UTC, chavlji approved these changes
Great job! Works as expected.

Please add a separate ticket for this:
1. Would be cool to **emit some event on open/close**.
2. I'd say we only have to emit an event on close arrow click and let the app handle the closing... app might have decided that the drawer shouldn't be closed (due to unsaved changes) or it might need to destroy some elements on close.

2021-02-23 15:23 UTC, merged