PLAT-846: Add tree view
reciprocity/zen-ui pull request #202
Opened 2021-02-25 09:00 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-846)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-03-01 11:31 UTC, chavlji commented
@mihaelpalfi 
1. no. Let's keep it per row.
2. I have a solution with cell content position: absolute. Can I push it?

2021-03-01 15:30 UTC, chavlji requested changes

2021-03-01 15:30 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  traverseOnClose(): void {
Rename to what it actually does - `closeDescendants()`

2021-03-01 15:30 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +    // Get all rows that have depth greater then the parent
Code would be a lot more readable and you wouldn't need this comment if you'd extract gathering descendats into separate function:
`this.descendants().forEach(n => n.expanded = false);`

2021-03-01 15:30 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +    this.children().forEach(child => (child.visible = expanded));
I think this doesn't work ok. Try it in some story.

2021-03-01 15:30 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly selectable = false;
I'd rename it to `hasCheckbox`

2021-03-01 15:30 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly slotted = false;
Why do we need this?

2021-03-01 15:30 UTC, chavlji commented on src/components/zen-table/zen-table.stories.mdx
> +      <sb-zen-table-row depth="2" selectable>
Please use `map` loop for such highly repetative stories. It's hard to read and maintain. Create array and map items from it.

2021-03-02 05:49 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  traverseOnClose(): void {
Done

2021-03-02 05:51 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +    // Get all rows that have depth greater then the parent
You are right. Done.

2021-03-02 06:42 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly slotted = false;
Leftover. Wanted to add this if we wand full width of the cell.

2021-03-02 06:44 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly selectable = false;
Hmm dont know but for me this is more suited. And in vue it also uses selectable.

2021-03-02 09:00 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly selectable = false;
Do you mean our vue listing? But it's funny, because in description you're stating just that: "Show checkbox" 😂 
I always prefer prop names that doesn't leave doubt. I connect `selectable` with disabled state of whole row...
Anyway, let's vote and see.

2021-03-02 09:21 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly selectable = false;
`selectable` upvoted. Keep it!

2021-03-02 18:18 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Prop() readonly selectable = false;
Done

2021-03-02 20:25 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +    this.children().forEach(child => (child.visible = expanded));
Seems it works. Whats the reason you think it dosent?

2021-03-02 20:26 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.stories.mdx
> +      <sb-zen-table-row depth="2" selectable>
Next pr.

2021-03-03 09:00 UTC, mplesec reviewed
The implementation is sound, but I've encountered some bugs? And I think one breaking change to current functionality, but I'm not sure it's caused by this PR.

One of the visual tests incorrectly updates the snapshot, as the new snapshot doesn't match what's in storybook:
![Screenshot 2021-03-03 at 09 52 36](https://user-images.githubusercontent.com/9392804/109780200-0e367f80-7c07-11eb-8478-f3ef57a08091.png)

The titles for this story look out of place:
![Screenshot 2021-03-03 at 09 53 06](https://user-images.githubusercontent.com/9392804/109780307-2efed500-7c07-11eb-8241-36c8b2a8cf64.png)

The sticky header needs a background:

https://user-images.githubusercontent.com/9392804/109780385-42aa3b80-7c07-11eb-9064-4f44cc6c7ad1.mov

2021-03-03 09:31 UTC, mihaelpalfi commented on src/components.d.ts
> +          * Visible if no !depth or parent.expanded (read-only)
Changed.

2021-03-03 09:32 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.scss
> +@for $i from 0 through 32 {
For now its ok. We will probably move this so it will be added dynamically.

2021-03-03 09:53 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.scss
> +.expendable {
Done.

2021-03-03 11:08 UTC, mihaelpalfi commented
> The implementation is sound, but I've encountered some bugs? And I think one breaking change to current functionality, but I'm not sure it's caused by this PR.

1. The vrt screnshot is correct. I removed some rows.
2. The miss aligment issue. It looks ok for me. Only the first row left padding is off and have to still figure it out how to change this without braking thee tree css. Will do this in next pr. 
3. Fixed the sticky issue. Added z index and fixed some css on the header row cell.

2021-03-03 13:24 UTC, mplesec approved these changes

2021-03-04 08:37 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +    this.children().forEach(child => (child.visible = expanded));
Because it won't close all decendents but just direct children.

2021-03-04 08:39 UTC, chavlji commented on src/components/zen-table/zen-table.stories.mdx
> +      <sb-zen-table-row depth="2" selectable>
Please add link to ticket in this case here.

2021-03-04 08:43 UTC, chavlji requested changes

2021-03-04 08:43 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  /** Visible if no depth or parent.expanded */
You're not reacting to changes of this attr from apps side, so please mark it as `read-only` in the description.

2021-03-04 08:44 UTC, chavlji commented
Please don't forget to add link to ticket for `Please use map loop for such highly repetative stories...` here

2021-03-04 09:55 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.stories.mdx
> +      <sb-zen-table-row depth="2" selectable>
Added to this ticket PLAT-1340

2021-03-04 09:58 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  /** Visible if no depth or parent.expanded */
Done

2021-03-04 09:58 UTC, mihaelpalfi commented
> Please don't forget to add link to ticket for `Please use map loop for such highly repetative stories...` here

https://reciprocitylabs.atlassian.net/browse/PLAT-1340

2021-03-04 11:15 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +    this.children().forEach(child => (child.visible = expanded));
Fixed

2021-03-04 14:28 UTC, chavlji approved these changes
🚢 it!

2021-03-04 14:28 UTC, merged