PLAT-1340:  Add selectable highlighted
reciprocity/zen-ui pull request #213
Opened 2021-03-05 09:07 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1340)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-03-16 07:55 UTC, chavlji commented
A few bugs that should be resolved before diving into code review:

1. Child rows shouldn't be expanded when the parent row is expanded.
2. Collapsed child node's background is white, even though it's not a root row.
https://user-images.githubusercontent.com/5729421/111273553-417c0400-8634-11eb-93d5-19c27e06411f.mov

3. Parent's checkbox doesn't get updated when children selected state changes. I don't think this is a task for this PR, so please create a ticket and add a link below.
https://user-images.githubusercontent.com/5729421/111273925-ac2d3f80-8634-11eb-8c35-a8c9638d33b0.mov

4. Is this spacing really ok? Seems like gap between dropdown arrow and label is really big (1.)
5. Spacing between checkbox and label is even bigger in case row has no children (2.). Please talk to designers how this should be done.
![Screenshot 2021-03-16 at 08 51 31](https://user-images.githubusercontent.com/5729421/111274432-468d8300-8635-11eb-9953-a8507f19d27f.jpg)

2021-03-16 07:57 UTC, chavlji requested changes
A few bugs that should be resolved before diving into code review:

1. Child rows shouldn't be expanded when the parent row is expanded (video under pt. 2 attached).
2. Collapsed child node's background is white, even though it's not a root row (video attached).
https://user-images.githubusercontent.com/5729421/111273553-417c0400-8634-11eb-93d5-19c27e06411f.mov

3. Parent's checkbox doesn't get updated when children selected state changes. I don't think this is a task for this PR, so please create a ticket and add a link below.
https://user-images.githubusercontent.com/5729421/111273925-ac2d3f80-8634-11eb-8c35-a8c9638d33b0.mov

4. Is this spacing really ok? Seems like gap between dropdown arrow and label is really big (Pt. 1 on image under pt. 5)
5. Spacing between checkbox and label is even bigger in case row has no children (Pt. 2 on image under pt. 5). Please talk to designers how this should be done.
![Screenshot 2021-03-16 at 08 51 31](https://user-images.githubusercontent.com/5729421/111274432-468d8300-8635-11eb-9953-a8507f19d27f.jpg)

2021-03-17 08:30 UTC, mihaelpalfi commented
> A few bugs that should be resolved before diving into code review:

1. Fixed the children expanding issue.
2. Fixed together
3. Next PR for intermediate state.
4. Fixed together
5. Fixed together

2021-03-17 11:59 UTC, chavlji commented on src/components/zen-table/zen-table.tsx
> +  descendants(target: HTMLZenTableRowElement): HTMLZenTableRowElement[] {
rename to `rows`

2021-03-17 14:31 UTC, chavlji requested changes
Getting there. It works much better now!

But this PR is waaay too long! 750 lines. It's impossible to review carefully. Description of what this code does is scattered all over the place (a little in jira, a bit in pr description, a few bulletins in comments...). Next time please chop it into smaller PRs.

One thing to fix:
1. Popovers are covered with the next rows
![Screenshot 2021-03-17 at 12 54 35](https://user-images.githubusercontent.com/5729421/111463703-28508180-8720-11eb-90ab-43263cfead85.jpg)
This happens because you have `transform: scale(1)` on table row. But if you don't have it, row doesn't have `position: relative` and you can't position elements absolutely... It's quite a big problem.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
>    children(): HTMLZenTableRowElement[] {
Shouldn't this be named `descenants`? Children are direct children, so outDepth+1. Descendants are items inside this row on any depth.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
>      // Get all rows that have depth greater then the parent
Invalid comment if this function returns children.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  onSelect(): void {
Is this triggered if you call `document.querySelector('#my-row').selected = true` somewhere in my code?

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +  onExpand(): void {
This isn't triggered if you call `document.querySelector('#my-row').expanded = true` somewhere in the code.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
>    @Prop() readonly fullSpan = false;
Where is this used?

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
>    @Prop() readonly depth: number = 0;
Check that it works correctly if you call `document.querySelector('#my-row').depth = 15` somewhere from eg. some button click handler. I think you need watchers for most of these props.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/test/zen-table-row.spec.tsx
> +  it('should render checkbox', async () => {
Add more tests. Current coverage is 69%.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.stories.mdx
> +### 1. Single row
You can remove those stories. Keep just story with controls. All of these stories are alreday presented in the table stories page.

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.stories.mdx
> +<Meta title="Tables/Table Row" component="zen-table-row" argTypes={argTypes} />
Add all table components stories to `Lists/Table/Row`, `Lists/Table/Header`, `Lists/Table/Table`

2021-03-17 14:31 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +      expandable: this.expandable,
As mentioned in previous Prs... use `reflect` and attribute selectors and don't tranform props into classes.

2021-03-17 15:38 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +  descendants(target: HTMLZenTableRowElement): HTMLZenTableRowElement[] {
Done

2021-03-17 15:39 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +  @Listen('rowSelected')
Done

2021-03-17 15:45 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +        n.classList.add('expanded-bg');
It was there but then it didn work correctly. The expanded inner child lost the background on close.

2021-03-17 16:32 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +    target.expanded = expanded;
Moved the logic for setting expandable and selectable to row and header. Also cleaned up the handler part.

2021-03-17 17:00 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
>    @Prop() readonly depth: number = 0;
I added property  mutable to expanded and selected. I needed it because of the change addressed up.

2021-03-17 17:04 UTC, mihaelpalfi commented on src/components/zen-table-row/test/zen-table-row.spec.tsx
> +  it('should render checkbox', async () => {
This is a subtask PLAT-1537

2021-03-17 17:05 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.stories.mdx
> +### 1. Single row
Dont agree. The stories should contain the component possibilities. In the table component they are all joined together.

2021-03-17 17:26 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +      expandable: this.expandable,
Uff if i start changing this on all files i have work for 2 days :) Because css will stop working and like you know i will struggle. I can create a new ticket maybe.

2021-03-17 17:27 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +    target.selected = selected;
Changed.

2021-03-17 17:27 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +    target.selected = selected;
changed.

2021-03-17 17:32 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +    let next = target.nextElementSibling as HTMLZenTableRowElement;
Done

2021-03-17 17:36 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
> +  rows(): HTMLZenTableRowElement[] {
Hmm you suggested to be rows. Going in circle. :) In my opinion and how Leo mentioned on your pr it should be getRows.

2021-03-17 17:40 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
> +  allSelectedRows(): boolean {
Thats why you use "get" in the names returning something and here "has". But again this variable name  was your suggestion. :) Changed to hasAllRowsSelected, hasRowsSelected, hasExpandableRows.

2021-03-17 17:41 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
> +    this.headerSelected.emit(!this.selected);
Yes changed. Before i had issues doing it like a toggle. But i think that was another issue that resolved it now.

2021-03-17 17:44 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
>      forEach(elements, setSticky);
Done

2021-03-17 17:44 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +    this.rowExpanded.emit(!this.expanded);
Yes done

2021-03-17 17:52 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  @Event() rowSelected: EventEmitter<boolean>;
Changed to rowSelectChange, rowExpandChange

2021-03-17 18:02 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
>    setSticky(): void {
Is this not handled if the prop is mutable?

2021-03-17 18:20 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
> +      subtree: true,
Removed. Still works.

2021-03-17 18:26 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
>    @Prop() readonly fullSpan = false;
You are right only in the css. Removed

2021-03-18 08:15 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
>    children(): HTMLZenTableRowElement[] {
Hmm this are direct children??

2021-03-18 08:15 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
>      // Get all rows that have depth greater then the parent
removed

2021-03-18 08:26 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +  expandedChanged(target: HTMLZenTableRowElement, expanded: boolean): void {
This is a separate pr.

2021-03-18 10:36 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  onSelect(): void {
Added new PLAT-1541

2021-03-18 10:36 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +  onExpand(): void {
Added new PLAT-1541

2021-03-18 10:37 UTC, mihaelpalfi commented on src/components/zen-table-header/zen-table-header.tsx
> +  @Prop() readonly selected: boolean = false;
Added new PLAT-1541

2021-03-18 11:50 UTC, chavlji requested changes
A few minor changes left, then we can merge.

**Regarding this:**
_Thats why you use "get" in the names returning something and here "has". But again this variable name was your suggestion. :) Changed to hasAllRowsSelected, hasRowsSelected, hasExpandableRows._

That's not true. Check git blame. It's your code.
The point is that in English you ask questions like: "Are all rows selected?" and not "Are all selected rows?". Second question has a different meaning which means function name is not describing what the function actually does, which is a bad practice.
In your new change word order is ok.

2021-03-18 11:50 UTC, chavlji commented on src/components/zen-table/zen-table.tsx
> +        n.classList.add('expanded-bg');
Css must have been wrong then. Try something like this:
`:host([depth]:not([depth=0])), :host(.expanded) { background-color: $gray; }`

2021-03-18 11:50 UTC, chavlji commented on src/components/zen-table-header/zen-table-header.tsx
> +  rows(): HTMLZenTableRowElement[] {
ok

2021-03-18 11:50 UTC, chavlji commented on src/components/zen-table-row/test/zen-table-row.spec.tsx
> +  it('should render checkbox', async () => {
Haven't we all agreed that tests should be written in the same pr? If we don't agree, we have to discuss it again. In this particular case, do it in a separate pr.

2021-03-18 11:50 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.stories.mdx
> +### 1. Single row
Ok. From story 2, please remove header and keep just one row. What I've meant is that focus here should be on one row only so it's not confused with the table. How table header and selectable row look like is already presented in the table story page.

2021-03-18 11:50 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> +      expandable: this.expandable,
Add new ticket then and paste link here.

2021-03-18 11:55 UTC, mihaelpalfi commented on src/components/zen-table-row/test/zen-table-row.spec.tsx
> +  it('should render checkbox', async () => {
Didnt know we agreed to this. When?

2021-03-18 11:57 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.stories.mdx
> +### 1. Single row
Done.

2021-03-18 11:58 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> +      expandable: this.expandable,
PLAT-1548

2021-03-18 12:09 UTC, mihaelpalfi commented on src/components/zen-table/zen-table.tsx
> +        n.classList.add('expanded-bg');
Done.

2021-03-18 12:18 UTC, chavlji approved these changes

2021-03-18 12:18 UTC, merged