PLAT-1541: Add  properties watch
reciprocity/zen-ui pull request #248
Opened 2021-03-21 17:38 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1541)

#### Description
As per JIRA ticket

- Moved row selected logic from table to row watch selected
- Moved row expanded logic from table to row watch selected
- Cleaned up the components code and added descriptions

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-03-25 20:05 UTC, homer0 approved these changes
Seems to keep working as expected 🤘 - I just left a single comment (multiple times) regarding some validations :P.

2021-03-25 20:05 UTC, homer0 commented on src/components/zen-table-header/zen-table-header.tsx
> +      }
I meesed up... I was reviewing only one commit :P.

I already left two comments regarding this kind of `if`s, it should be a couple of files below.

2021-03-26 10:54 UTC, chavlji requested changes
Very nice! Works as expected!

I've spotted little inconsistecy:
Sometimes clicking indeterminate checkbox checks all children, while other time it unchecks all of them. It should always select all when clicking indeterminate checkbox.

https://user-images.githubusercontent.com/5729421/112620563-009ca000-8e29-11eb-9265-5a56bf6f5484.mov

Another question: Do we still need prop `row.indeterminate`? If I set it programmatically it just messes the state. I guess that's again the question of who's controlling the state. But in this case I think the component is in charge, so there's no point to expose it to the app.

2021-03-26 10:54 UTC, chavlji commented on src/components/zen-table-row/zen-table-row.tsx
> + * @method parentRow | Returns parent row
You don't have to manually document methods and events created with Stencil's decorators `@Method` and `@Event`. Just slots and events triggered manually with native dispatch.
```suggestion
```

2021-03-26 17:40 UTC, homer0 commented
To @chavlji 's comment:

> Another NIT: Do we still need prop row.indeterminate? If I set it programmatically it just messes the state. I guess that's again the question of who's controlling the state. But in this case I think the component is in charge, so there's no point to expose it to the app.

If removing it simplifies the state, go for it and we can think of `indeterminate` as a computed value :D.

2021-03-29 11:27 UTC, mihaelpalfi commented on src/components/zen-table-row/zen-table-row.tsx
> + * @method parentRow | Returns parent row
Removed

2021-03-29 15:18 UTC, homer0 commented
- The table row is still showing the `indeterminate` prop on the story.
- Not sure if the tests are failing because of the change or if it's a random error :P.

2021-03-30 08:54 UTC, mihaelpalfi commented
> * The table row is still showing the `indeterminate` prop on the story.
> * Not sure if the tests are failing because of the change or if it's a random error :P.

1. Removed the prop from row story.
2. Fixed header story so test are now ok.

2021-03-30 10:40 UTC, chavlji approved these changes
I'm approving this, just for sake to get it over and merge it finally.

But I really strongly disagree with hiding props. Consumer has now no way to find out that he can at least read props `expended`, `depth`, `visible`,... they're not not documented anywhere. Sole purpose of storybook is to automate these docs and we're now adding a bunch of expectations that adds to confusion. If we don't want enduser to set them, prefix them with `$` or mention in the description that it's preferable to not set those props.

I've added tasks to improve these things:
https://reciprocitylabs.atlassian.net/browse/PLAT-1667
https://reciprocitylabs.atlassian.net/browse/PLAT-1668

2021-03-30 10:43 UTC, merged

2021-03-30 10:45 UTC, mihaelpalfi commented
> I've added tasks to improve these things:
> https://reciprocitylabs.atlassian.net/browse/PLAT-1667
> https://reciprocitylabs.atlassian.net/browse/PLAT-1668

Good Jan. now its in my opinion a little more manageable, so that we dont have everything in one pr.

2021-03-30 10:48 UTC, chavlji commented
@mihaelpalfi I agree!

2021-03-31 15:10 UTC, zenbot-0 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- `1.0.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: