PLAT-844: Skeleton component
reciprocity/zen-ui pull request #249
Opened 2021-03-22 03:42 UTC by f-jauregui

⚠️  Unified the component to be flexible and easy to use. This is also an exploration so please feel free to comment if you think this approach is not good enough. ⚠️ 

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-844)

#### Description
As per JIRA ticket. 

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-03-22 15:49 UTC, homer0 reviewed
LGTM :D; I'll leave the :shipit: when the tests are added.

2021-03-23 11:35 UTC, chavlji commented on src/components/zen-skeleton/zen-skeleton.scss
> +  &::before {
Nice solution using pseudo!

2021-03-23 11:41 UTC, chavlji requested changes
Nice! Very clean and simple solution! Just a few minor tweaks...

2021-03-23 11:41 UTC, chavlji commented on src/components/zen-skeleton/zen-skeleton.scss
> +  &::before {
Nice solution using pseudo!

2021-03-23 11:41 UTC, chavlji commented on src/components/zen-skeleton/zen-skeleton.tsx
> +  @Prop({ reflect: true }) readonly isRounded: boolean = false;
rename to `rounded`

2021-03-23 11:41 UTC, chavlji commented on src/components/zen-skeleton/zen-skeleton.tsx
> +  @Prop() readonly width: string = '100%';
I'd revemo this. Imo it's useless to duplicate suff that you can easily do with inline styling: `style="width: 100%; height:100%"`.

2021-03-23 11:41 UTC, chavlji commented on src/components/zen-skeleton/test/zen-skeleton.spec.tsx
> +  it('should render a skeleton circle', async () => {
No need to test. Reflect is stencil's functionality.

2021-03-23 19:53 UTC, chavlji approved these changes

2021-03-23 19:54 UTC, merged