BAN-53: Basic Input with Label and Support Text
reciprocity/zen-ui pull request #25
Opened 2020-12-01 01:16 UTC by f-jauregui

[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-53)

2020-12-01 08:04 UTC, chavlji requested changes

2020-12-01 08:04 UTC, chavlji commented on src/components/zen-input/zen-input.tsx
> +            <label>
I know this is a wip, but just a note here:
Label and supporting text are not part of this component. We said they will be standalone components and wrapped with a 4th component called ZenFormGroup.

2020-12-02 14:28 UTC, chavlji requested changes

2020-12-02 14:28 UTC, chavlji commented on src/components/zen-input/zen-input.tsx
> +  @Prop() required = false;
You're not emitting any events. How will consumers know what's the value?
Also pay attention on how to get that value from FromGroup? Shouldn't be problems since we're using slots I guess...

2020-12-02 14:28 UTC, chavlji commented on src/components/zen-input/zen-input.stories.ts
> +  argTypes,
Please add all/most props to playground, so we can test if everything works directly from storybook.

2020-12-02 14:28 UTC, chavlji commented on src/components/zen-input/zen-input.scss
> +  &:hover {
This should probabbly go to our input mixin?
Also :focus, :disabled,...

2020-12-02 14:28 UTC, chavlji commented on src/components/zen-input/zen-input.stories.ts
> +  return html` <zen-input placeholder="Insert text here..." /> `;
I'm unable to use keyboard keys 'space', 'left arrow', 'right arrow',... inside input in any story?

2020-12-02 14:28 UTC, chavlji commented on src/components/zen-input-support-text/zen-input-support-text.scss
> +  font-size: 0.75rem;
Please use $text-sm

2020-12-02 15:35 UTC, chavlji commented
One more thing to pay attention to; I think input should have width: 100% by default.

Otherwise consumers can't control the width. With setting input with to 100%, input will follow the container (container = actual component that app can control = `<zen-input style="width: 500px" />`).

We have to keep that in mind for all the components.

2020-12-02 16:52 UTC, f-jauregui commented on src/components/zen-input/zen-input.stories.ts
> +  return html` <zen-input placeholder="Insert text here..." /> `;
Not sure what you mean with this one

2020-12-02 18:46 UTC, chavlji commented on src/components/zen-input/zen-input.stories.ts
> +  return html` <zen-input placeholder="Insert text here..." /> `;
I open go to input story, focus input, write 'abc123' - all good. I then (still inside input) press `space` - it writes nothing, but scrolls to end of the page.
In story for *form group* same thing happens. And one more: if I press `arrow left/right`, text carret is supposed to move left/right. But it does nothing.
I can record video, but you won't know which key's I'm pressing...

2020-12-03 13:53 UTC, f-jauregui commented on src/components/zen-input/zen-input.stories.ts
> +  return html` <zen-input placeholder="Insert text here..." /> `;
This was working fine. Resolved.

2020-12-03 16:28 UTC, chavlji approved these changes
Can be merged, but please create a ticket for the requested in this case and place their links under the comments (to track it better).

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/test/zen-input.spec.tsx
> +describe('zen-input', () => {
Tests for all 4 components are covering just the default setup and aren't checking props/variants/events.
Add a separate task, to cover that for all 4 components.

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input-label/zen-input-label.tsx
> +@Component({
There's no documentation for zen-input-label nor zen-input-support-text. Nowhere to see available options. Create a task for this please.
Where do we put docs for these micro components? It's kinda ugly to list them separately without a context because there'll be a ton of them, but I can't see any other option atm.

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input-label/zen-input-label.tsx
> +  tag: 'zen-input-label',
zen-form-group-label would be better name, because you control can also be dropdown, checkbox, textarea, radios, ...
If you agree, please create a task for this.

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input-label/zen-input-label.tsx
> +  @Prop() readonly text: string = null;
name 'label' would be better

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/zen-input.tsx
> +    return typeof this.value === 'number' ? this.value.toString() : (this.value || '').toString();
shouldn't we rather check input's attr type?

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/zen-input.tsx
> +  @Prop() readonly required = false;
prop 'type' is missing

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/zen-input.tsx
> +          type="text"
we should support other types

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/zen-input.stories.ts
> +    control: {
this isn't necessary. It can figure out that it's a boolean prop. You only need to specify some special ones like color picker.

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/zen-input.stories.ts
> +    type: { name: 'string', required: false },
this isn't needed... It can figure it out automatically.

2020-12-03 16:28 UTC, chavlji commented on src/components/zen-input/zen-input.stories.ts
> +const argTypes = {
You can remove whole argTypes obj, since it only has basic stuff that it can automatically figure out from passed default arguments for component.
Check zen-steps stories.

2020-12-03 16:28 UTC, chavlji commented on src/zen-styles/mixins/forms.scss
> +  margin: .5rem 0;
Remove these margins. Put it into zen-form-group. Components shouldn't define it's outside layout.

2020-12-03 16:28 UTC, chavlji commented on src/zen-styles/mixins/forms.scss
> +  &::placeholder {
Nice!

2020-12-03 16:55 UTC, f-jauregui commented on src/components/zen-input/zen-input.tsx
> +    return typeof this.value === 'number' ? this.value.toString() : (this.value || '').toString();
no, this is the default component value

2020-12-03 16:56 UTC, f-jauregui commented on src/components/zen-input-label/zen-input-label.tsx
> +  tag: 'zen-input-label',
zen-label will be better

2020-12-03 16:57 UTC, f-jauregui commented on src/components/zen-input/test/zen-input.spec.tsx
> +describe('zen-input', () => {
Yes, we should do that in all components

2020-12-03 16:59 UTC, f-jauregui commented on src/components/zen-input/zen-input.tsx
> +  @Prop() readonly required = false;
Automatically inferred, since is a boolean there is no other valid option. And actually linter will complain about that.

2020-12-03 16:59 UTC, f-jauregui commented on src/components/zen-input/zen-input.tsx
> +          type="text"
As requirement comes in will do

2020-12-03 17:24 UTC, f-jauregui commented on src/components/zen-input/zen-input.stories.ts
> +const argTypes = {
argTypes obj defautValues is the way to do it.
https://storybook.js.org/docs/react/api/argtypes

2020-12-03 17:25 UTC, f-jauregui commented on src/components/zen-input/zen-input.stories.ts
> +    control: {
you still need to specify it as argument, and inside argTypes object is the way to do it

2020-12-03 17:33 UTC, f-jauregui commented on src/components/zen-input/test/zen-input.spec.tsx
> +describe('zen-input', () => {
https://reciprocitylabs.atlassian.net/browse/BAN-86

2020-12-03 17:35 UTC, merged

2020-12-03 18:32 UTC, chavlji commented on src/components/zen-form-group/zen-form-group.stories.ts
> +      <zen-input style="margin: .5rem 0;"></zen-input>
This margin should be set from form-group.css, because we want to have standardized spacings in all form groups.
You can use `::slotted()` selector for that.