PLAT-1606: Add avatar details variant basic
reciprocity/zen-ui pull request #264
Opened 2021-03-25 11:03 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1606)

#### Description
As per JIRA ticket

![image](https://user-images.githubusercontent.com/59830865/112462990-04192400-8d62-11eb-9c40-f2eee41a49f2.png)

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-03-25 17:44 UTC, homer0 reviewed
It looks good overall 🤘, just left a few small comments on the "execution".

2021-03-25 17:44 UTC, homer0 commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +    if (this.variant == 'detailed') return textSize;
```suggestion
    if (this.variant === 'detailed') return textSize;
```

2021-03-25 17:44 UTC, homer0 commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +  textSize(): string {
This is just a suggestion that I consider good practice: use verbs as prefixes for methods/functions (like get/set/change/update/etc.) and leave nouns for properties && getters/setters. For example, in this case, it would be `getTextSize`.

2021-03-25 17:44 UTC, homer0 commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +    }
You could implement a private _map_ for these, something like this:

```js
const basicTextSizeByDetailSize = {
  sm: 'md',
  md: 'lg',
  lg: 'xl',
};
```

And then just return `basicTextSizeByDetailSize[this.variant]`.

2021-03-25 17:44 UTC, homer0 commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          vertical-align={this.variant == 'basic' ? 'center' : 'start'}
I'm seeing too many ternaries; you can do something like the sizes dictionary I suggested on the method for the text size:

```js
const propsByVariant = {
  basic: {
    mainVerticalAlignment: 'center',
    avatarSize: null, // so you can short circuit with this.size (prop.avatarSize || this.size),
    usernameBold: false,
  },
  detailed: {
    mainVerticalAlignment: 'start',
    avatarSize: 'md',
    usernameBold: true,
  },
}
```

It will not only get rid of the ternaries, but it will reduce the number of possible branches and reaching good coverage will be easier 😉 .

2021-03-26 05:37 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +  textSize(): string {
Heh this is my opinion as well. But on other prs Jan dosent want this naming. Maybe my coding style is to old school and this has changed in the years. I will change it.

2021-03-26 10:09 UTC, chavlji requested changes
A few minor changes...

2021-03-26 10:09 UTC, chavlji commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          spacing={this.spacing}
I realy strongly believe we should remove prop `spacing`. In all official designs it seems like variant basic has spacing 8 px and detailed variant has 12 px.
https://www.figma.com/file/rWXEQiJcBXbkMY8V4NSM1d/ZenGRC-Component-Library?node-id=2629%3A3519

2021-03-26 10:09 UTC, chavlji commented on src/components/zen-avatar-details/zen-avatar-details.stories.mdx
> +        <sb-zen-avatar-details
Change to `lg` size. Designs provide only `md` and `lg` size.

2021-03-26 10:09 UTC, chavlji commented on src/components/zen-avatar-details/zen-avatar-details.stories.mdx
> +### 1. Avatar details variants
NIT: Can be just simply "Variants"

2021-03-26 11:01 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +    if (this.variant == 'detailed') return textSize;
Done

2021-03-26 11:06 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +    }
Done

2021-03-26 11:19 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +  @Prop() readonly size: IconSizes = 'md';
In my opinion would not go into direction what designers want regarding this case regarding naming and possibilities. Consumer should be able to chose from possible icon sizes.

2021-03-26 11:31 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.stories.mdx
> +### 1. Avatar details variants
Done

2021-03-26 11:38 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          spacing={this.spacing}
This inconsistency is weird. Added a question for Shelley on wire frames if this is intentional.

2021-03-27 06:42 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          vertical-align={this.variant == 'basic' ? 'center' : 'start'}
Good suggestion. I changed it. But not quite sure if i changed it in a correct way.

2021-03-29 11:03 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +  @Prop() readonly size: IconSizes = 'md';
Removed

2021-03-29 11:04 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          spacing={this.spacing}
Shelley answered that it was a mistake. Its the same spacing for both. She updated the wireframes.

2021-03-29 11:05 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.stories.mdx
> +        <sb-zen-avatar-details
Removed size. Now we have three variants. Detailed, basic default and basic large.

2021-03-29 15:36 UTC, homer0 commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +    const propsByVariant = {
1. This could be class property: since it doesn't change, we don't need to re define it on each call.
2. Instead of calling the function for each property, we could probably define a type for the dictionary:

```
type VariantSizes = {
  verticalAlignment: string;
  ...
}

...

getSizesByVariant(): VariantSizes { ... }
```

2021-03-29 15:36 UTC, homer0 commented on src/components/helpers/types.ts
> +export type AvatarDetailVariant = 'basic_default' | 'basic_large' | 'detailed';
Is there a reason we are using _snake_case_ for this instead of _dash-case_?

2021-03-29 16:35 UTC, mihaelpalfi commented on src/components/helpers/types.ts
> +export type AvatarDetailVariant = 'basic_default' | 'basic_large' | 'detailed';
Cant create object name with dash-case.

2021-03-29 17:36 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +    const propsByVariant = {
Done

2021-03-29 21:05 UTC, homer0 approved these changes
Tiny changes, but this is looking good 🤘!

2021-03-29 21:05 UTC, homer0 commented on src/components/helpers/types.ts
> +export type AvatarDetailVariant = 'basic_default' | 'basic_large' | 'detailed';
But you can do it with quotes:

```js
'basic-default': { verticalAlignment: 'center', avatarIconSize: 'sm', userNameBold: false, textSize: 'md' }
```

I don't like it either, but I think it's a small price to pay for consistency :P.

2021-03-29 21:05 UTC, homer0 commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          vertical-align={this.getPropsByVariant().verticalAlignment}
Why don't you call it only once and keep the reference?

```js
const sizes = this.getPropsByVariant();

...

<ZenSpace
  ...
  vertical-align={sizes.verticalAlignment}
>
```

2021-03-30 08:42 UTC, mihaelpalfi commented on src/components/zen-avatar-details/zen-avatar-details.tsx
> +          vertical-align={this.getPropsByVariant().verticalAlignment}
Done

2021-03-30 08:42 UTC, mihaelpalfi commented on src/components/helpers/types.ts
> +export type AvatarDetailVariant = 'basic_default' | 'basic_large' | 'detailed';
Done.

2021-03-30 11:18 UTC, chavlji requested changes
Very clean PR! Great!

Just one minor thing to be more consistent...

2021-03-30 11:18 UTC, chavlji commented on src/components/helpers/types.ts
> +export type AvatarDetailVariant = 'basic-default' | 'basic-large' | 'detailed';
nit: Please rename to `basic`, `basic-lg` and `detailed`

2021-03-30 11:23 UTC, mihaelpalfi commented on src/components/helpers/types.ts
> +export type AvatarDetailVariant = 'basic-default' | 'basic-large' | 'detailed';
Done.

2021-03-30 11:31 UTC, chavlji approved these changes

2021-03-30 11:31 UTC, merged

2021-03-31 15:10 UTC, zenbot-0 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- `1.0.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: