BAN-79: Add recommended Stencil lint rules
reciprocity/zen-ui pull request #27
Opened 2020-12-02 11:16 UTC by chavlji

[jira](https://reciprocitylabs.atlassian.net/browse/BAN-79)

Check commit messages for more info.

2020-12-02 11:31 UTC, f-jauregui approved these changes

2020-12-02 11:31 UTC, f-jauregui commented on src/components/zen-animate/zen-animate.tsx
> +    if (!slot) return;
Nice!

2020-12-02 14:25 UTC, mplesec requested changes

2020-12-02 14:25 UTC, mplesec commented on .eslintrc.js
> +    'plugin:prettier/recommended',
Pretty sure this needs to be last.

2020-12-02 14:25 UTC, mplesec commented on .eslintrc.js
> +    // Stencil rules:
Aren't these applied by default?

2020-12-03 09:59 UTC, chavlji commented on .eslintrc.js
> +    // Stencil rules:
[Should be](https://github.com/ionic-team/stencil-eslint#recommended-rules) yeah.
But I don't know why it's not working. Eg. if I remove `'@stencil/props-must-be-readonly': 'error',` from specific rules list, it won't show eslint error 🤔

2020-12-03 13:05 UTC, merged