PLAT-1605: Add title and hyperlink to tooltip
reciprocity/zen-ui pull request #274
Opened 2021-03-31 09:23 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1605)

#### Description
As per JIRA ticket

![image](https://user-images.githubusercontent.com/59830865/113121915-6dda7780-9213-11eb-8d03-d23ec56f1643.png)

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-03-31 13:49 UTC, homer0 approved these changes
🤘
![image](https://user-images.githubusercontent.com/6949310/113154680-a0ce3c80-920e-11eb-93be-5250434a7c99.png)

It seems that it has the same "issue" as the avatar detail (shorter body makes the title multiline), but that can taken on a different ticket/PR, as the scope of this one is already covered.

2021-03-31 14:15 UTC, chavlji requested changes
Very nice and clean!

2021-03-31 14:15 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +  cursor: grab;
```suggestion
  cursor: pointer;
```
😂

2021-03-31 14:15 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +Set property header and link.
```suggestion
Set property `header` and/or `link`.
```

2021-04-01 05:38 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  cursor: grab;
uppss. Changed.

2021-04-01 05:41 UTC, mihaelpalfi commented on src/components.d.ts
> +        "header": string;
Renamed.

2021-04-01 05:42 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +Set property header and link.
Done

2021-04-01 05:44 UTC, mihaelpalfi commented
> 🤘
> ![image](https://user-images.githubusercontent.com/6949310/113154680-a0ce3c80-920e-11eb-93be-5250434a7c99.png)
> 
> It seems that it has the same "issue" as the avatar detail (shorter body makes the title multiline), but that can taken on a different ticket/PR, as the scope of this one is already covered.

Shouldn't it go to new line?

2021-04-01 06:26 UTC, chavlji approved these changes

2021-04-01 06:26 UTC, merged

2021-04-01 06:29 UTC, zenbot-0 commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- `1.1.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: