PLAT-1611: inputs: add size prop
reciprocity/zen-ui pull request #280
Opened 2021-03-31 19:21 UTC by chavlji

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1611)

2021-03-31 22:12 UTC, homer0 reviewed
This is looking great 🤘!

2021-03-31 22:12 UTC, homer0 commented on src/components/zen-dropdown/test/zen-dropdown.spec.tsx
> +    await render();
Why not moving it to the `beforeEach`?

2021-03-31 22:12 UTC, homer0 commented on src/components/zen-dropdown/zen-dropdown.stories.mdx
> +- Set `size` to `custom` in order. It will make dropdown's height equal to height selected option.
I think there's something missing here "...to `custom` in order...", in order to do what? :P

2021-03-31 22:12 UTC, homer0 commented on src/components/zen-dropdown/zen-dropdown.tsx
> +    const iconSize = this.size === 'sm' ? 'sm' : 'md';
Ha! this is what I suggested on the previous comment xD.

2021-03-31 22:12 UTC, homer0 commented on src/components/zen-menu-item/zen-option.stories.mdx
> +- Zen-option ships in different sizes
I've seen that you used this phrase in multiple places, and I think it doesn't fully _transmit_ what you are trying to say. What do you think about doing something like this:

```
This component supports multiple sizes through the use of the `size` attribute, but it is only considered when implemented with "default items" (simple text), and in that case, you need to make sure you set the same `size` on the `zen-dropdown`.
```

I know this can't be applied the same way on all the cases, but I just wanted to give you an example of how to phrase it like a message rather than a requirement list... and yes, I know that a requirement list for a library makes more sense, but it's a lot easier for the implementation when the connection between the "requirements" is explicit.

Anyways, let know what do you think :D

2021-04-01 06:36 UTC, chavlji commented on src/components/zen-date-picker/zen-date-picker.tsx
> +
Good points. Fixed.
Initially, I was thinking that testing will be easier with a separate method, but since it's not public it's not easier 😛

2021-04-01 06:38 UTC, chavlji commented on src/components/zen-dropdown/test/zen-dropdown.spec.tsx
> +    await render();
Because I send initial params as args to render function. I can't do that elegantly with beforeEach (not without global var hack).

2021-04-01 08:05 UTC, mihaelpalfi requested changes
Looking fantastic. Tested on firefox and edge. Found only two issues : 
1. In Firefox story title overlaps opened dropdown.
![image](https://user-images.githubusercontent.com/59830865/113262930-75f8ec80-92d1-11eb-8d0c-299d3ffb2122.png)

2. When I set menu width to 50% the size of menu is not correct.
![image](https://user-images.githubusercontent.com/59830865/113263036-9759d880-92d1-11eb-88bd-b56186d34b8a.png)

2021-04-01 08:56 UTC, chavlji commented
@mihaelpalfi Thanks. Fixed!

2021-04-01 09:03 UTC, mihaelpalfi approved these changes
LGTM

2021-04-01 09:04 UTC, merged

2021-04-01 09:08 UTC, zenbot-0 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `2.0.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: