PLAT-1755: Add tabs component
reciprocity/zen-ui pull request #301
Opened 2021-04-08 05:35 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1755)

@chavlji 
1. I have one issue cant figure out why tabSelected event is not bubbling up from the tab component. Everything works, just dont see the event in the story. Tried to trigger a new one directly int the tabs component. Nothing.
2. There is some funny business going on with the tabs and the storybook. If you try to change the "value" param, It is used somewhere in the story folder document. Jan maybe you have more context why is that there?  

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-04-08 09:35 UTC, chavlji requested changes
Looks nice and works as expected. One minor improvement though...

2021-04-08 09:35 UTC, chavlji commented on src/components/zen-tab/zen-tab.tsx
> +      <Host class={{ selected: this.selected }} onClick={() => this.onClick()}>
When you promote `selected` to prop, you should just reflect it instead of converting to class.

2021-04-08 09:35 UTC, chavlji commented on src/components/zen-tab/test/zen-tab.spec.tsx
> +  it('should select', async () => {
If you reflect `selected` you don't need to check this.

2021-04-08 09:35 UTC, chavlji commented on src/components/zen-tab/zen-tab.tsx
> +  @Method()
Promote `selected` to prop and set watcher for it. Then you can remove methods `select` and `deselect`. Components should "follow props down, events up" if possible.

2021-04-08 11:24 UTC, mihaelpalfi commented on src/components/zen-tab/zen-tab.tsx
> +      <Host class={{ selected: this.selected }} onClick={() => this.onClick()}>
done

2021-04-08 11:32 UTC, mihaelpalfi commented on src/components/zen-tab/test/zen-tab.spec.tsx
> +  it('should select', async () => {
done

2021-04-08 11:33 UTC, mihaelpalfi commented on src/components/zen-tab/zen-tab.tsx
> +  @Method()
removed

2021-04-08 12:34 UTC, chavlji approved these changes
Looks great! 😎

2021-04-08 14:08 UTC, homer0 commented
@mihaelpalfi Looks great... but :P:

1. I don't see any commit with the `BREAKING CHANGE:` comment, and the `zen-tabs` implementation is completely different now.
2. Can you change the PR target to the `breaking` branch? so we can release it today with the rest of the breaking changes.

2021-04-08 14:27 UTC, mihaelpalfi commented
> @mihaelpalfi Looks great... but :P:
> 
> 1. I don't see any commit with the `BREAKING CHANGE:` comment, and the `zen-tabs` implementation is completely different now.
> 2. Can you change the PR target to the `breaking` branch? so we can release it today with the rest of the breaking changes.

We can. But my opinion is that this tabs were in the "in progress" in the story book before and is not used nowhere right now. I have only one thing to push when its reviewed. Move it to the navigation part of the story book.

2021-04-08 18:38 UTC, homer0 approved these changes

2021-04-08 18:41 UTC, homer0 commented
@mihaelpalfi Ok, that's fine for this case, but we shouldn't publish stuff in which we are not going to respect SemVer; the version/changelog is what should tell implementation whether or not something changed, not a section of Storybook.

Also, not a blocker (I already sent the approval), but shouldn't the tabs component emit a change event? Otherwise, the implementation would have to add `onClick` on each tab.

2021-04-09 12:32 UTC, chavlji commented
@mihaelpalfi can we merge this?

2021-04-09 13:17 UTC, merged

2021-04-09 13:19 UTC, zenbot-0 commented
:tada: This PR is included in version 3.2.0 :tada:

The release is available on:
- `3.2.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/3.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: