PLAT-1667: Table: indeterminate state inconsistent
reciprocity/zen-ui pull request #304
Opened 2021-04-09 06:09 UTC by chavlji

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1667)

#### Description
As per JIRA ticket

2021-04-09 12:56 UTC, f-jauregui approved these changes
What an awesome job, Jan! 🥇 
Love that observer and that updates everything in bulk.

2021-04-09 13:49 UTC, mihaelpalfi requested changes
Great and fast work Jan. And fantastic idea with table editor! Focused more on testing the functionality.  Found some issues
1.  With the header row transition from indeterminate state to checked (chrome).

https://user-images.githubusercontent.com/59830865/114190113-396d6680-994b-11eb-8eeb-cf586eeff19f.mov

2. Probably the same issue when deselecting the second level child the state of main parent checkbox dosent change. 

https://user-images.githubusercontent.com/59830865/114189981-180c7a80-994b-11eb-86fd-07465d373da9.mov

2021-04-09 18:57 UTC, homer0 reviewed
![image](https://user-images.githubusercontent.com/6949310/114227465-6b7ec880-994b-11eb-9858-d834da2655de.png)

I just left a couple of syntax-based comments :P.

Also, I believe the issues @mihaelpalfi reported are fixed on #305 , as I just tested it and I couldn't reproduce the erros from the videos.

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/test/zen-table.spec.tsx
> +global.console = { error: jest.fn() };
You should use a spy instead of overwriting the global console, otherwise you would kill the functionality even for the runner:

```js
const spy = jest.spyOn(console, 'error');
```

And since you are only validating it on a single test, I would suggest that you create the spy only in that test.

2021-04-09 18:57 UTC, homer0 commented on src/components/helpers/helpers.ts
> +export function htmlToElement(html: string): Element[] {
Why are we shipping stuff that's only meant for the tests and Storybook? My concern is that, if we ship it, we have to maintain it, meaning that changes on this function will affect the versioning of the package, when we don't actually expect for implementations to use it.

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/test/zen-table.spec.tsx
> +global.MutationObserver = mutationObserverMock();
If there's no other way and you have to overwrite a global object, what you normally do is: you keep a reference of the original, replace it on `beforeEach` and restore it on `afterEach`, that way, the tests don't affect any other tests/functionality that may use/check the property:

```js
import { mutationObserverMock } from '../../helpers/jest';
const originalMutationObserver = global.MutationObserver;

describe('zen-table', () => {
  beforeEach(() => {
    mutationObserverMock.mockClear();
    global.MutationObserver = mutationObserverMock();
  });
  
  afterEach(() => {
    global.MutationObserver = originalMutationObserver;
  });
});
```

The idea is that tests cases should, when possible, avoid at all costs to modify the environment outside their execution.

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/zen-table-helpers.tsx
> +  function parentRows(rows, index: number): HTMLZenTableRowElement[] {
- Why did you define other functions inside `cleanupTableStructure`? None of them use the `table` parameter. They could be non-exported functions.
- I would recommend you that, if you don't need to use `this`, you should use an arrow function. It's just a little, but arrow functions can generate a smaller "footprint" on the generated bundle, as they can be optimized in ways regular functions can't (like removing parentheses, brackets and/or the `functions and `return` keywords. The only difference is that arrow functions don't have context

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/zen-table-helpers.tsx
> +export const cleanupTableStructure = async function (table: HTMLZenTableElement): Promise<void> {
Is there a need for this to be `async`? I don't see any use of promises/`await`.

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/zen-table-helpers.tsx
> +    // Apprently their parent got deleted so we'd expect they'd get too.
This is very informative, so maybe you should move it to the JSDoc block for the function, that way IDEs can pick it.

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/zen-table-helpers.tsx
> +export const allRows = function (table: HTMLZenTableElement): HTMLZenTableRowElement[] {
```suggestion
export const getAllRows = function (table: HTMLZenTableElement): HTMLZenTableRowElement[] {
```

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/zen-table-helpers.tsx
> +  function isNormalRow(element: HTMLZenTableRowElement) {
Like above, no need to re define the function on each call if there's no use of the context:

```js
const isNormalRow = (element: HTMLZenTableRowElement): boolean => element.tagName.endsWith('-ROW') && !element.header;
export const getAllRows = (table: HTMLZenTable): HTMLZenTableRowElement[] => (Array.from(table.children) as HTMLZenTableRowElement[]).filter(isNormalRow);
```

2021-04-09 18:57 UTC, homer0 commented on src/components/zen-table/zen-table.tsx
> +  childObserver: MutationObserver = null;
```suggestion
  private childObserver: MutationObserver = null;
```

2021-04-12 07:31 UTC, chavlji commented on src/components/zen-table/test/zen-table.spec.tsx
> +global.console = { error: jest.fn() };
If I don't overwrite it, we get console.error in the output which I think will crash tests on the ci:
![Screenshot 2021-04-12 at 09 18 11](https://user-images.githubusercontent.com/5729421/114355749-238cbb00-9b70-11eb-81e3-c321c42bbdd8.jpg)
I've ended up mocking an unlocking `console.error` on each test.

2021-04-12 07:44 UTC, chavlji commented on src/components/zen-table/zen-table-helpers.tsx
> +  function parentRows(rows, index: number): HTMLZenTableRowElement[] {
- I always do that. I think it's more clear this way, these functions are (for now) only used inside this one function.
- Until now I always did right the opposite. I only used arrow functions if I needed to persist the scope of the "parent" function. It's also easier to extract function this way if we also need it somewhere else later.
  - I've changed it now and will try to follow your pattern.

2021-04-12 08:03 UTC, chavlji commented on src/components/helpers/helpers.ts
> +export function htmlToElement(html: string): Element[] {
I'm opening a new ticket for that. How do we exclude it from bundle?
https://reciprocitylabs.atlassian.net/browse/PLAT-1811

2021-04-12 08:06 UTC, chavlji commented
@mihaelpalfi First issue should be gone in https://github.com/reciprocity/zen-ui/pull/305
The second issue isn't an issue. In this case, only the direct child has all children selected, so only this one will get checked checkbox. Other parents should have an indeterminate checkbox as they do.

2021-04-12 10:56 UTC, mihaelpalfi approved these changes

2021-04-12 10:57 UTC, merged

2021-04-12 11:00 UTC, zenbot-0 commented
:tada: This PR is included in version 3.2.3 :tada:

The release is available on:
- `3.2.3`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/3.2.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-04-12 16:20 UTC, homer0 commented on src/components/zen-table/zen-table-helpers.tsx
> +  function parentRows(rows, index: number): HTMLZenTableRowElement[] {
Not a big deal, but functions shouldn't be used for scoping, as you would end up re defining them each time it gets called, and in this case, the function is called pretty often.

If non-exported functions are not your thing, you could use any of these:

- Modules: Yes, you still have non-exported functions, but with a single context; something like `zen-table/helpers/cleanupTableStructure` and only export the main function.
- Static class: you can use methods (even private methods) for the utility functions. The only "downside" is that if you want to export only one method, you have to bind it, for example: `export const cleanTableStructure = Cleaner.clean.bind(Cleaner)` (where `Cleaner` is the name of the class).