PLAT-1773: When clear button is clicked on zen-input a change event is triggered
reciprocity/zen-ui pull request #306
Opened 2021-04-11 23:28 UTC by f-jauregui

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/)

⚠️ **NOTE: Nor onClick and onMouseup worked on this component, not sure if it's a Stencil bug.** ⚠️ 

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-04-12 08:55 UTC, chavlji requested changes
Nice. Two comments:
1. `input` event should be fired as well. As by definition
2. _"The input event fires when the value of an <input>, <select>, or <textarea> element has been changed."_ - from [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event))
2. On date picker we get 2 change events on clear click. Could you please investigate why?

2021-04-12 12:19 UTC, mihaelpalfi approved these changes
Looks good. Change event triggered. Can confirm two events fired in date picker. I assume the issue is that it is logged for the input component and the date picker component. So story book.

2021-04-12 13:13 UTC, f-jauregui commented
@chavlji I asked for your review again because as @mihaelpalfi said, I think the double change event is caused by Storybook.

2021-04-12 14:15 UTC, chavlji approved these changes
Ok. If you have some time, please investigate why it's called twice in the storybook.

2021-04-12 15:55 UTC, homer0 commented
It shouldn't have an `input` event; `input` is for user interaction, changing the value programmatically doesn't trigger it. This button is similar to `<input type="reset" />`, and if you listen for `input` and `change` events on an input that can be reset, the only triggered event is `change`.

Regarding the double event, is it possible that they are the `change` from the input and the `change` triggered from picker itself?

2021-04-13 13:23 UTC, f-jauregui commented
> It shouldn't have an `input` event; `input` is for user interaction, changing the value programmatically doesn't trigger it. This button is similar to `<input type="reset" />`, and if you listen for `input` and `change` events on an input that can be reset, the only triggered event is `change`.
> 
> Regarding the double event, is it possible that they are the `change` from the input and the `change` triggered from picker itself?

@chavlji @homer0 Should I roll back the last commit?

2021-04-14 08:12 UTC, chavlji approved these changes
Nice! Works as expected.
I'd just put back this test and then you can merge it! 🚢

2021-04-14 08:12 UTC, chavlji commented on src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
> -  it('should not render x button if allowEmpty is false', async () => {
I'd still test this? Test just if zen-input has attr `clear-button` set. Jic someone messes up your attr binding...

2021-04-14 19:47 UTC, homer0 commented on src/components/zen-date-picker/tests/zen-date-picker.spec.tsx
> -  it('should not render x button if allowEmpty is false', async () => {
Agree, even if the button is on another component, we should test that the attr set on the picker reflects correctly on the input attrs.

2021-04-14 19:48 UTC, homer0 approved these changes

2021-04-15 18:19 UTC, merged

2021-04-15 18:25 UTC, zenbot-0 commented
:tada: This PR is included in version 3.5.0 :tada:

The release is available on:
- `3.5.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/3.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: