New textarea component
reciprocity/zen-ui pull request #31
Opened 2020-12-07 09:10 UTC by f-jauregui

[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-59)

In draft because need to **add tests**.

2020-12-08 14:45 UTC, chavlji requested changes

2020-12-08 14:45 UTC, chavlji commented on src/components/zen-textarea/readme.md
> +# zen-textarea
Remove this row

2020-12-08 14:45 UTC, chavlji commented on src/components/zen-input-label/zen-input-label.tsx
> +import { Component, h, Prop } from '@stencil/core';
This one is also from rebase right?

2020-12-08 14:45 UTC, chavlji commented on src/components/zen-textarea/zen-textarea.tsx
> +
I think we also need at least `backgroundColor` prop. `color` isn't needed because it's inherited from the host and the app can set the propper color with style attr.

2020-12-08 14:46 UTC, f-jauregui commented on src/components/zen-input-label/zen-input-label.tsx
> +import { Component, h, Prop } from '@stencil/core';
Yes 🤦

2020-12-08 14:49 UTC, f-jauregui commented on src/components/zen-textarea/zen-textarea.tsx
> +  @Prop() readonly cols = 30;
Do you think that will be better if I just remove that and we keep with 100% and which height?

2020-12-08 15:11 UTC, f-jauregui commented on src/components/zen-textarea/zen-textarea.tsx
> +  @Event() zenTextarea!: EventEmitter<KeyboardEvent>;
Can't be called input because it collides con native implementation.

2020-12-08 15:14 UTC, f-jauregui commented on src/components/zen-textarea/readme.md
> +# zen-textarea
BTW these things are autogenerated when you run yarn build or yarn start for the first time.

2020-12-09 09:00 UTC, chavlji requested changes

2020-12-09 14:35 UTC, f-jauregui commented on src/components/zen-textarea/zen-textarea.tsx
> +  @Event() keyboardInput!: EventEmitter<KeyboardEvent>;
After a sync we agreed to standarize named event names like **zenInput** or **zenChange**

2020-12-09 14:54 UTC, f-jauregui commented
We have to merge #32 first because it has zen-form-group implementation. After that merge I'll rebase this one 😄

2020-12-09 15:08 UTC, chavlji approved these changes
Nice!

2020-12-09 15:08 UTC, chavlji commented on src/components/zen-textarea/zen-textarea.scss
> +  height: 5rem;
This won't follow :host. Is there any way to make it work? Even setting :host flex with align-items, justify-content stretch...

2020-12-10 07:09 UTC, merged