BAN-54: New checkbox component
reciprocity/zen-ui pull request #32
Opened 2020-12-07 09:39 UTC by f-jauregui

[Jira ticket](https://reciprocitylabs.atlassian.net/browse/BAN-54)

Draft PR because it **needs more tests**.

2020-12-08 13:44 UTC, chavlji requested changes

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-checkbox/readme.md
> +# zen-checkbox
Remove this line

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox-interface.ts
> +export interface CheckboxChangeEventDetail {
I'd call files like this `helpers.ts` or `types.ts` so it's unified throughout the components.

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +        <input type="checkbox" class="input-control" disabled={this.disabled} checked={this.checked} />
Checkbox component should also accept prop `label`. That's a basic thing that we should support. Clicking of label should un/check box.

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  @Event() zenChange!: EventEmitter<CheckboxChangeEventDetail>;
Conventional names as `input` or `change` would be better. No need for the prefix here.

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  @Prop() readonly value = 'on';
Do we need this property? Why isn't `checked` enough?

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-input-label/zen-input-label.tsx
> +@Component({
We're getting a mess with this micro components. We should think how to categorize them before tomorrow's presentation. At least start grouping them in lhn.
Why do we have both `zen label` and `zen input label`?

2020-12-08 13:44 UTC, chavlji commented on src/components/zen-input-label/readme.md
> +# zen-input-label
Remove this line

2020-12-08 13:58 UTC, f-jauregui commented on src/components/zen-input-label/zen-input-label.tsx
> +@Component({
No, I'll remove it. That shouldn't be there. Maybe was added after the rebase.

2020-12-08 13:58 UTC, f-jauregui commented on src/components/zen-input-label/readme.md
> +# zen-input-label
This will be removed. We only need zen-label.

2020-12-08 14:41 UTC, f-jauregui commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  @Prop() readonly value = 'on';
Actually it is

2020-12-08 14:52 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  /**
nit: These comments takes up so much space... I'd prefere them as single lines eg. `/** This prop does that */`

2020-12-08 15:08 UTC, chavlji requested changes
Much better! A few more changes though...

2020-12-08 15:08 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +        {this.label ? <zen-label label={this.label} /> : null}
1. Don't use zen-label here. It's a totally different element. It's also styled differently (is't bold as zen-label is). Just use native label element...
2. Make sure it looks disabled when component is disabled

2020-12-08 15:08 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +
We're missing prop `required`. It should also draw asterisk next to label.

2020-12-08 15:08 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  @Prop() readonly disabled = false;
In story I can still un/check checkbox even if it's disabled.

2020-12-08 15:08 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.stories.ts
> +    description: 'set if the input is checked',
Remove description here. We'll have `description` and `defaultValue` for props in Properties table.

2020-12-08 15:19 UTC, f-jauregui commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  @Event() change!: EventEmitter<CheckboxChangeEventDetail>;
That's why I was changing the event name.

2020-12-08 15:26 UTC, f-jauregui commented on src/components/zen-checkbox/zen-checkbox.tsx
> +  @Prop() readonly disabled = false;
Well... It's re-rendering the component right?
That's just to display styles not to test events.

2020-12-09 08:19 UTC, chavlji requested changes
1. Label isn't aligned with checkbox:
![Screenshot 2020-12-09 at 08 45 23](https://user-images.githubusercontent.com/5729421/101600197-3f822380-39fb-11eb-92d3-beb2ec21a5c2.jpg)

2. Line-height should following inc/decrease of font size:
![Screenshot 2020-12-09 at 08 45 13](https://user-images.githubusercontent.com/5729421/101600201-4315aa80-39fb-11eb-8ff2-01641d00f8b2.jpg)

3. Check that it works within formGroup - top label is probably redundant, but message below is useful. Add propper styling to formGroup.

2020-12-09 08:19 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.stories.ts
> +export default {
When you use `Default.args` you can remove whole Argtypes thing. It will pick up propper control type automatically.

2020-12-09 08:21 UTC, chavlji commented on src/components/zen-checkbox/zen-checkbox.stories.ts
> +  checked = checked ? checked : false;
Use `Default.args` instead of this kind od setting the defaults. See steps component.

2020-12-09 15:00 UTC, chavlji approved these changes
🚢  it!

2020-12-09 15:00 UTC, chavlji commented on src/components/zen-form-group/zen-form-group.stories.ts
> +    <zen-form-group>
It's great that you've put them all in one story. It looks awesome!

2020-12-09 15:03 UTC, merged