PLAT-1815: Add status tracker component
reciprocity/zen-ui pull request #328
Opened 2021-04-21 16:47 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-1815)

#### Description
As per JIRA ticket

![image](https://user-images.githubusercontent.com/59830865/115591064-01164280-a2d2-11eb-8de4-12b421b34a0c.png)

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-04-21 17:32 UTC, homer0 reviewed
A few comments, mostly syntax-wise, but looks great 🤘!

2021-04-21 17:32 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  }
I have a few suggestions for this method:

- I would separate the loop for when it's archived, that way you don't have to do early exit on every iteration and, since the amount of things it does is just two lines, it will be easier to read.
- Instead of keeping the flag outside the iteration, you could use a reducer and use it as the accumulator.
- When changing the `variant` of the selected, you could use a ternary for the value.
- `===` > `==` :P.
- Try to avoid, if possible, "ternary lines"; they are really hard to differentiate from assignments xD. For a second, I thought you were overwriting the index with the result of `setAttribute` :P.
- When adding the transparent border, you could also check if `index` is truthy, because there's no way the selected one will be `-1`.

Based on those comments, I did this:

```ts
  setChildStyles(): void {
    if (this.archived) {
      this.children.forEach(lozenge => {
        lozenge.setAttribute('variant', 'none');
        lozenge.setAttribute('size', 'lg');
      });

      return;
    }

    this.children.reduce((hasSelected, lozenge, index) => {
      lozenge.setAttribute('size', 'lg');
      const isSelected = this.selected === index;
      if (isSelected) {
        hasSelected = true;
        lozenge.setAttribute(
          'variant',
          index === this.children.length - 1 ? 'green' : 'dark-blue-ghost'
        );
      } else {
        lozenge.setAttribute('variant', 'none');
      }

      if (hasSelected && !isSelected) lozenge.setAttribute('disabled', '');
      if (index && this.selected === index - 1) {
        lozenge.style.borderLeft = '1px solid transparent';
      }

      return hasSelected;
    }, false);
  }
```

To be clear: **It's not "change it to look like that**; the only blocker comments are the `===` and the "ternary line", for the rest, take or ignore what you think it's best, those are just suggestions.

(Too many meetings, I wanted to code something :P).

2021-04-21 17:32 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +    this.children = Array.from(this.host.children).map(n => n as HTMLZenLozengeElement);
Not sure if this is the place, but we should probably validate something like

```js
if (this.selected > this.host.children.length - 1) {
  throw new Error("There's no lozenge at the selected index");
}
```

What do you think?

2021-04-21 17:47 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +    this.children = Array.from(this.host.children).map(n => n as HTMLZenLozengeElement);
Would not do that. I would like to set like "-1" if a case comes up that nothing should be selected. But would validate if no children were added. Added.

2021-04-21 17:52 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  }
Good fed-back! Not so skilled yet. Changed

2021-04-21 17:57 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.stories.mdx
> +<Meta title="Navigation/Status Tracker" component="zen-status-tracker" argTypes={argTypes} />
All other components titles are in uppercase. Its the progress tracker issue. :)

2021-04-21 18:15 UTC, chavlji requested changes
Works ok, but I'd set things a bit differently.

We're mixing 2 approaches: semantic web and reactive framework component approach. Since we have a semantic approach here, we should let things be set on children and loosen the control from the parent.

2021-04-21 18:15 UTC, chavlji commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +    if (this.host.children.length == 0) throw new Error("There's no lozenge children");
This function should run in mutation observer. Currently it will only run on load and if lozenges are added/deleted during this component's lifespan, state won't be updated.

2021-04-21 18:15 UTC, chavlji commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly selected: number = 0;
Why do we need this prop? It would be better to put this prop to lozenga component instead.
User could just add lozenge with the correct attributes.
Imo this component should only take care of correctly showing dividers. If we wouldn't have those, we wouldn't even need this component. Container with display:flex row would be enough...

2021-04-21 18:15 UTC, chavlji commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly archived: boolean = false;
Same as selected. Put this into lozenga component instead.

2021-04-22 04:16 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly selected: number = 0;
I kind of disagree... but I initially thought of the same thing :P.

First, I thought it didn't make a lot of sense  to make the component reusable, as you said, the dividers it's the only "feature" that provides and the rest could be solved with `flex-direction: row`... but then, it was confirmed that there will be multiple cases for this, which can mean multiple apps, so it was bound to have repetition.

Now, the product team designed this component as a composition of specific states (color), variants (size) and order (`archived`), and thinking on multiple implementations, it makes sense for it to already have its logic defined in a single place that can easily maintained.

If we were to only take care of the dividers, we would be splitting the component responsibilities into multiple places: The lozenge for the archived, this component for the dividers and the implementation for the states; that's too many places to maintain a single functionality, even one as small as this one.

We can discuss this further on the sync.

2021-04-22 04:17 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly archived: boolean = false;
Same argument as above :P

2021-04-22 05:33 UTC, chavlji commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly selected: number = 0;
@homer0  I also gave this a further thought yesterday afterward :) My base argument would be just to relieve this component of so many responsibilities. But I totally agree with your reusability argument.

If it will stay like this we need to fix this, to work as expected:
1. `selected` prop should be item `id` and not just index (if user mutates children, the incorrect item might be highlighted)
2. `selected` and `archived` classes/styles should be recalculated in mutation observer (basically the same thing as in my first comment)

2021-04-22 05:46 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly selected: number = 0;
Awesome :D.

1. Up to you guys, I have no strong preference over that; the only thing is that we'll also need to validate that all children have an `id` attribute.
2. Agree 👍

2021-04-26 15:05 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly selected: number = 0;
Done

2021-04-26 15:05 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +  @Prop() readonly archived: boolean = false;
Done

2021-04-26 15:40 UTC, homer0 approved these changes
🤘!!! (Small syntax-releated comment)

2021-04-26 15:40 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +      console.error('zen-status-tracker: Not all of `zen-lozenge`elements have id defined!!', this.host);
```suggestion
      console.error('zen-status-tracker: Not all of `zen-lozenge` elements have id defined!!', this.host);
```

2021-04-26 15:40 UTC, homer0 commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +    if (!this.hasChildren()) {
I agree with what we discussed on the daily about having the `has[x]` and the `get[x]` in separated methods, in this case, I don't see a point on having a method for only one execution context: `hasChildren` is only being used in this method, but then we are using another method (`hasIdsSet`) that also needs the children.

I would recommend doing something like you did on `setLozengeProperties`, capture the children and then use them multiple times:

```js
const children = this.getChildren();

if (!children.length) {
  ...
}

if (!children.every(item => item.hasAttribute('id')) {
  ...
}

...
```

2021-04-26 15:41 UTC, homer0 commented
@mihaelpalfi If you are ready to merge and the `coverage` job keeps failing for the same thing, you can ignore it... that's on coveralls.

2021-04-26 17:27 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +      console.error('zen-status-tracker: Not all of `zen-lozenge`elements have id defined!!', this.host);
Fixed

2021-04-26 17:30 UTC, mihaelpalfi commented on src/components/zen-status-tracker/zen-status-tracker.tsx
> +    if (!this.hasChildren()) {
Changed.

2021-04-26 18:04 UTC, merged

2021-04-26 18:06 UTC, zenbot-0 commented
:tada: This PR is included in version 5.1.0 :tada:

The release is available on:
- `5.1.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/5.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: