QUICK-FIX(zen-tabs): prevent selected tab jumping
reciprocity/zen-ui pull request #329
Opened 2021-04-22 09:23 UTC by chavlji

Eliminate ugly tabs jumping when selecting a tab. Uses `text-shadow` instead `font-weight`.
Difference is imo very hard to notice even if you compare it side by side:
![Screenshot 2021-04-22 at 11 20 28](https://user-images.githubusercontent.com/5729421/115690197-18e6d880-a35d-11eb-8b2e-bfa31d59fd7e.jpg)

2021-04-22 12:44 UTC, mihaelpalfi approved these changes

2021-04-22 12:54 UTC, f-jauregui requested changes
I'm not sure about this, changes in the typography silhouette are noticeable. There's no way to prevent the jump without a hack?

2021-04-22 14:08 UTC, chavlji commented
@f-jauregui Not an easy one.

We would need to make original content transparent. Then we should add content duplicate absolutely positioned in place of original content. And duplicated content should have `font-weight: bold`.

But text is not just a text. It's a slot. So we'd need to copy a slot and if user would update the original slot content... 🐇 🕳️

2021-04-26 15:49 UTC, homer0 commented
Moving this `WIP` until Jan gets back.

2021-05-04 08:18 UTC, chavlji commented
I'm closing this one since the solution is not ideal. The best solution would be to rethink the design and to not use bold text in such cases (unselected - normal, selected - bold).

2021-05-04 08:18 UTC, closed without merging