PLAT-2013: Add system tooltip variant and arrow
reciprocity/zen-ui pull request #352
Opened 2021-05-24 08:38 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2013)

#### Description
As per JIRA ticket

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-05-24 15:51 UTC, homer0 commented on src/components/zen-tooltip/zen-tooltip.tsx
> +    this.variantChanged(this.variant);
Not sure if the watch is due to a convention you were using, but in this case, you don't need it: changing the attribute will already trigger a re-render, so you can have a map of the backgrounds and get the right now, with fallback to `default`, on `render`:

```ts
private backgroundByVariant: Record<TooltipVariant, string> = {
  system: '#1E272C',
  default: '#FFFFFF',
};
// The, on render:
const backgroundColor = this.backgroundByVariant[this.variant] || this.backgroundByVariant.default;
```

I just tested it and it seems to work :D.

The reason I added the comment is not because of the syntax, but since `render` gets triggered anyways, whether you watch the attribute or not, I would assume that one less watcher would be better for performance :P.

2021-05-25 06:12 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +    this.variantChanged(this.variant);
Yes it was a convention. But i also dont think this watchers are needed. Changed and added also additional parameter for arrow.

2021-05-25 06:34 UTC, homer0 approved these changes
🤘

2021-05-25 08:29 UTC, chavlji commented on src/components/scss/vars/shadows.scss
> +$shadow-drop-300: 0px 2px 5px 1px rgba($color-blue-800, 0.15);
nit: We could mention it's blue color in the name? Like $shadow-drop-blue-300

2021-05-25 08:37 UTC, chavlji approved these changes
Nice! Just a few nits if you have time...

2021-05-25 08:37 UTC, chavlji commented on src/components/scss/vars/shadows.scss
> +$shadow-drop-300: 0px 2px 5px 1px rgba($color-blue-800, 0.15);
nit: We could mention it's blue color in the name? Like $shadow-drop-blue-300

2021-05-25 08:37 UTC, chavlji commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +  it('should render variant system', async () => {
No need for this test. It only tests Stencil's mechanism for converting props to attrs.
Test if `backgroundColor` and `showArrow` is set correctly for variant `system` instead.

2021-05-25 08:37 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +          <sb-zen-tooltip position="top" label="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
nit: Please helper function `loremIpsum` from storybook utils.js to make it more readable.

2021-05-25 09:44 UTC, mihaelpalfi commented on src/components/scss/vars/shadows.scss
> +$shadow-drop-300: 0px 2px 5px 1px rgba($color-blue-800, 0.15);
removed. Not part of this ticket.

2021-05-25 09:48 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.stories.mdx
> +          <sb-zen-tooltip position="top" label="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
Heh. Didnt know this existed. Added.

2021-05-25 09:58 UTC, mihaelpalfi commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +  it('should render variant system', async () => {
Done

2021-05-25 10:34 UTC, Donaab requested changes

2021-05-25 10:34 UTC, Donaab commented on cypress/integration/visual/tooltip.e2e.js
> +    'story--notifications-tooltip--variant',
@mihaelpalfi Just skip the test for this story and I will fix it.

2021-05-25 10:34 UTC, mihaelpalfi commented on cypress/integration/visual/tooltip.e2e.js
> +    'story--notifications-tooltip--variant',
Done

2021-05-25 10:45 UTC, Donaab approved these changes

2021-05-25 10:45 UTC, merged

2021-05-25 10:47 UTC, zenbot-0 commented
:tada: This PR is included in version 6.6.0 :tada:

The release is available on:
- `6.6.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/6.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: