PLAT-2311: Add badge component
reciprocity/zen-ui pull request #355
Opened 2021-05-24 12:42 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/PLAT-2311)

#### Description
As per JIRA ticket

- initial implementation. probably need more specification like wireframes to know how should it work.

#### ChangeLOG

[Changelog](https://zen-ui.zengrc.com/?path=/docs/changelog--page)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-05-25 08:50 UTC, chavlji requested changes
Nice! Just a few minor changes...

2021-05-25 08:50 UTC, chavlji commented on src/components/zen-badge/zen-badge.stories.mdx
> +<Meta title="Containers/Badge" component="zen-badge" argTypes={argTypes} />
Please move it under `Graphics` section.
```suggestion
<Meta title="Graphics/Badge" component="zen-badge" argTypes={argTypes} />
```

2021-05-25 08:50 UTC, chavlji commented on src/components/zen-badge/zen-badge.tsx
> +  @Prop() readonly value: string | null = null;
No need for this prop. Value can/should be passed as default slot.

2021-05-25 08:50 UTC, chavlji commented on src/components/zen-tab/zen-tab.scss
> +  text-align: center;
Please add a task to remove prop `badge` from tab component.

2021-05-25 08:50 UTC, chavlji commented on src/components/zen-badge/zen-badge.scss
> +  text-align: center;
nit: Would be nice to also center it vertically in case we have some icons or something else in default slot. It can be overridden by consumer, but default value should be the most useful one:
```suggestion
  display: flex;
  align-items: center;
  justify-content: center;
```

2021-05-25 09:26 UTC, mihaelpalfi commented on src/components/zen-badge/zen-badge.stories.mdx
> +<Meta title="Containers/Badge" component="zen-badge" argTypes={argTypes} />
Done

2021-05-25 09:30 UTC, mihaelpalfi commented on src/components/zen-tab/zen-tab.scss
> +  text-align: center;
Done

2021-05-25 09:30 UTC, mihaelpalfi commented on src/components/zen-badge/zen-badge.tsx
> +  @Prop() readonly value: string | null = null;
Removed

2021-05-25 09:30 UTC, mihaelpalfi commented on src/components/zen-badge/zen-badge.scss
> +  text-align: center;
Addded

2021-05-25 09:37 UTC, chavlji commented
@mihaelpalfi @homer0 I don't think we need prop `visible`? We don't have it on any other graphical component (spinner, icon, lozenge,...). App can set `display: none` if it wishes to...

2021-05-25 09:40 UTC, chavlji approved these changes

2021-05-25 18:10 UTC, homer0 approved these changes

2021-05-26 03:41 UTC, merged

2021-05-26 03:43 UTC, zenbot-0 commented
:tada: This PR is included in version 6.7.0 :tada:

The release is available on:
- `6.7.0`
- [GitHub release](https://github.com/reciprocity/zen-ui/releases/tag/6.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: