BAN-58: Add tooltip component
reciprocity/zen-ui pull request #40
Opened 2020-12-09 07:50 UTC by mihaelpalfi

https://reciprocitylabs.atlassian.net/browse/BAN-58

2020-12-09 11:41 UTC, mplesec requested changes
Looking good, needs some fixes. Also didn't review the styles, perhaps someone else should do that since I don't know exactly the preferences around that.

Regarding the arrow position, I think we should use a position property instead. That way the component itself then handles both where the container is positioned and where the arrow is displayed on it. @chavlji @leferreyra opinions?

Regarding stories, also provide a story for how this works on an element. The example should allow user to hover over an element and see the tooltip display. Also the title of each one should be clearer, and probably doesn't need "Story" in it. 😅
![Screenshot 2020-12-09 at 12 36 21](https://user-images.githubusercontent.com/9392804/101625266-723c1400-3a1b-11eb-8371-8cae39792ebe.png)

2020-12-09 11:41 UTC, mplesec commented on src/components/zen-tooltip/zen-tooltip.tsx
> +        <span class={`${this.error ? 'error' : ''} ${this.arrow ? this.arrow : ''}`}>
NIT: Move this to a class method, it'll be easier to test.

2020-12-09 11:41 UTC, mplesec commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  /** Set text */
Add clearer descriptions for properties.

2020-12-09 11:41 UTC, mplesec commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  @Prop() readonly arrow?: ArrowPosition = ArrowPosition.LEFT;
The default for `arrow` property should probably be bottom since this is how it's displayed in the stories.

2020-12-09 11:41 UTC, mplesec commented on src/components/zen-tooltip/types.tsx
> +}
Total NIT, but I'd switch the LEFT and BOTTOM so it's consistent with how in i.e. CSS it expects these in clockwise order.
![Screenshot 2020-12-09 at 12 33 31](https://user-images.githubusercontent.com/9392804/101624876-e88c4680-3a1a-11eb-8d97-3b82392ae989.png)

2020-12-09 11:41 UTC, mplesec commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  @Prop() readonly error?: boolean = false;
Might be better to use a `variant` property to indicate different state instead of just an error prop.

2020-12-10 07:23 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.tsx
> +        <span class={`${this.error ? 'error' : ''} ${this.arrow ? this.arrow : ''}`}>
Or you can do the JSX way:

```jsx
<span class={{ 'error': this.error, this.arrow: this.arrow }}>
```

But I won't use `this.arrow`. Citing @mplesec:

> Regarding the arrow position, I think we should use a position property instead. That way the component itself then handles both where the container is positioned and where the arrow is displayed on it. @chavlji @f-jauregui opinions?

I agree with that, we should provide a `@Prop() position: string;` and depending on that the component itself will handle its position and where the arrow is displayed.

2020-12-10 07:44 UTC, f-jauregui requested changes
Just some tweaks, otherwise it looks really good to me. Good job, @mihaelpalfi!
Another good thing would be to provide a story when the tooltip is displayed along with other component, like a zen-button, so we can see it in action 😉

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.scss
> +  font-size: 0.75rem;
Use `$text-sm` variable.

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.scss
> +  color: #fff;
Nit, but $color-white.

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.tsx
> +        <span class={`${this.error ? 'error' : ''} ${this.arrow ? this.arrow : ''}`}>
Also when left and right positions: the arrow (and tooltip) should be centered relative to the item that will trigger the tooltip.

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.scss
> +  padding: 0.9375rem;
Use 1rem.

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.scss
> +  border-radius: 0.1rem;
You can consume $button-radius variable, but would be better to have a $border-radius-default since the same it's used across different components (And border-radius can be in pixels, for this variable case: 2px)

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.scss
> +  font-weight: 400;
Not necessary.

2020-12-10 07:44 UTC, f-jauregui commented on src/components/zen-tooltip/zen-tooltip.scss
> +  max-width: 11rem;
I would put this property into :host pseudo-class. In that way, max-width can be modified from outside targeting the just the component.

2020-12-10 13:36 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  /** Set text */
Done

2020-12-10 13:36 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  @Prop() readonly arrow?: ArrowPosition = ArrowPosition.LEFT;
Done

2020-12-10 13:37 UTC, mihaelpalfi commented on src/components/zen-tooltip/types.tsx
> +}
Done

2020-12-10 13:37 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  @Prop() readonly error?: boolean = false;
Done

2020-12-10 18:12 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +        <span class={`${this.error ? 'error' : ''} ${this.arrow ? this.arrow : ''}`}>
Moved class method.

2020-12-10 18:14 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  color: #fff;
done

2020-12-10 18:14 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  font-size: 0.75rem;
done

2020-12-10 18:14 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  padding: 0.9375rem;
done

2020-12-10 18:14 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  border-radius: 0.1rem;
done

2020-12-10 18:15 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  font-weight: 400;
removed

2020-12-15 10:52 UTC, mplesec approved these changes

2020-12-15 11:06 UTC, f-jauregui requested changes
Please remove `src/components/zen-tooltip/assets/profile.svg` it's adding 1.57MB to the final bundle. We should avoid using these asses that won't be used on production, place a dummy CSS circle (maybe with a letter) instead.

2020-12-15 11:57 UTC, chavlji requested changes
Nice! Needs just a bit of fine-tunning.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.stories.ts
> +    'The Manager can edit and create in the context of the PCI-DSS framework. They can also grant access to the framework to additional teammates.',
nit: Could this example text be max 50 chars long? It requires too much padding in the canvas.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/types.tsx
> +export enum Position {
Codebase is becoming cluttered with local type.ts files. Can you please move content of this file into `components/helpers/types.ts`, because variants, aligns, positions,... should have same possible values across all components.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +    expect(page.root).toEqualHtml(`
Tests are missing. Please add a ticket.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/mixins.scss
> +@mixin tooltip-variant($color, $background, $border) {
This mixin only adds complexity and masks what it really does. Remove it and write values directly in scss.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +  border-radius: 0.1rem;
I still see `border-radius: 0.1rem;`. It should be `border-radius: $border-radius-default` right?

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +  z-index: 999;
Let's create a variable `$z-index-tooltips` and add it to `zen-styles/variables.scss`

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +span:before {
Prefere syntax `&:before` inside previous span selector. It better resembles hierarchy of the rules.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +span {
Don't target element types. Rather append class and target it.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +  width: 0;
Why do you need that?

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  @Prop() readonly text?: string = '';
nit: I'd rename it to `label` since all other components use this name (button, dropdown, steps,...)

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.tsx
> +    this.element.style.display = 'none';
Instead of this add `@state visible` and then inside component:
`<Host class={{ visible: this.visible }}>` and add style `.visible { display: none; }`.
It will be more readable and easier to test.

2020-12-15 11:57 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +  display: block;
Don't use span with display: block. Use div instead which has display:block by default.

2020-12-15 12:00 UTC, chavlji commented
> Please remove `src/components/zen-tooltip/assets/profile.svg` it's adding 1.57MB to the final bundle. We should avoid using these asses that won't be used on production, place a dummy CSS circle (maybe with a letter) instead.

@f-jauregui why it adds to components bundle size if it's only used in storybook?

2020-12-15 12:03 UTC, mihaelpalfi commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +    expect(page.root).toEqualHtml(`
Look at the description of pr.

2020-12-15 12:22 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  border-radius: 0.1rem;
Waited for notifications to be merged. It had this variable.

2020-12-15 12:24 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.stories.ts
> +    'The Manager can edit and create in the context of the PCI-DSS framework. They can also grant access to the framework to additional teammates.',
Changed.

2020-12-15 13:22 UTC, mihaelpalfi commented on src/components/zen-tooltip/types.tsx
> +export enum Position {
Done

2020-12-15 13:26 UTC, mihaelpalfi commented on src/components/zen-tooltip/mixins.scss
> +@mixin tooltip-variant($color, $background, $border) {
Removed

2020-12-15 13:46 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +span {
Done

2020-12-15 13:47 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  width: 0;
For the arrow to be positioned correctly.

2020-12-15 14:02 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +  @Prop() readonly text?: string = '';
Renamed

2020-12-15 15:24 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  z-index: 999;
Done

2020-12-15 15:28 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +span:before {
Done.

2020-12-15 15:28 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.tsx
> +    this.element.style.display = 'none';
Done

2020-12-15 15:31 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  display: block;
Changed span to div.

2020-12-16 07:15 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.tsx
> +    this.element.style.display = 'none';
Great job!

2020-12-16 07:18 UTC, chavlji approved these changes
Great!

2020-12-16 07:18 UTC, chavlji commented on src/components/zen-tooltip/zen-tooltip.scss
> +  position: relative;
nit: You can then remove `display: block`, because div is block by default.

2020-12-16 07:19 UTC, chavlji approved these changes

2020-12-16 07:35 UTC, mplesec approved these changes

2020-12-16 10:08 UTC, mihaelpalfi commented on src/components/zen-tooltip/zen-tooltip.scss
> +  position: relative;
Will do in the ticket mentioned in the description.

2020-12-16 10:17 UTC, f-jauregui approved these changes
Great job, Mihael! 🚢

2020-12-16 10:18 UTC, merged