BAN-115: Add test cases to tooltip and Notifications
reciprocity/zen-ui pull request #80
Opened 2021-01-04 15:02 UTC by mihaelpalfi

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/BAN-115)

#### Description
As per JIRA ticket

#### ChangeLOG

- [ ] I have added all notable deployment/development environment (onprem!) changes to [CHANGELOG.md](https://github.com/reciprocity/zen-ui/blob/main/README.md)

#### Useful links
[Zen UI readme](https://github.com/reciprocity/zen-ui/blob/main/README.md)

[PR review guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/pull_request_reviews.md)

[Git commit guidelines](https://github.com/reciprocity/zengrc/blob/develop/doc/dev_environment_and_process/commit_guidelines.md)

2021-01-04 15:59 UTC, chavlji requested changes

2021-01-04 15:59 UTC, chavlji commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +  it.each(['top', 'right', 'bottom', 'left'])('Test each position %s is displayed correct', async position => {
nit: Test name should be `applies corret position attribute is %s`

2021-01-04 15:59 UTC, chavlji commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +    expect(page.root.getAttribute('position')).toEqual(position);
This test only checks if Stencil is applying the correct attribute. We should test our component.

2021-01-04 15:59 UTC, chavlji commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +    expect(page.root.getAttribute('variant')).toEqual(variant);
Same as for position test. This test isn't very useful.

2021-01-04 15:59 UTC, chavlji commented on src/components/helpers/types.ts
> +export type NotificationVariant = 'success' | 'info' | 'warning' | 'error';
Nice!

2021-01-06 07:05 UTC, mihaelpalfi commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +  it.each(['top', 'right', 'bottom', 'left'])('Test each position %s is displayed correct', async position => {
Changed

2021-01-06 07:05 UTC, mihaelpalfi commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +    expect(page.root.getAttribute('position')).toEqual(position);
You are right. Changed that it checks if correct class is applied.

2021-01-06 07:05 UTC, mihaelpalfi commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +    expect(page.root.getAttribute('variant')).toEqual(variant);
Same as above.

2021-01-06 07:06 UTC, mihaelpalfi commented on src/components/helpers/types.ts
> +export type NotificationVariant = 'success' | 'info' | 'warning' | 'error';
Still think that here should be an enum :)

2021-01-06 07:12 UTC, chavlji approved these changes

2021-01-06 07:12 UTC, chavlji commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +      }, 101);
Why 101? Doesn't it work if we lower that to eg. 10? Imo the point is just to postpone it to next cycle.

2021-01-06 07:13 UTC, chavlji commented on src/components/helpers/types.ts
> +export type NotificationVariant = 'success' | 'info' | 'warning' | 'error';
Agree with that. I'll take another look into that.

2021-01-06 09:05 UTC, mihaelpalfi commented on src/components/zen-tooltip/test/zen-tooltip.spec.tsx
> +      }, 101);
Because somebody implemented that it should wait 100ms before showing :)

2021-01-06 09:07 UTC, merged